#!/usr/bin/env python3
"""Add ALL remaining compounds to compound-tabs.tsx in one batch.
Uses careful string handling to avoid escape drift."""

import json

FILE = "src/data/compound-tabs.tsx"

with open(FILE, 'r') as f:
    content = f.read()

# Find the closing }; of compoundTabs
# It's followed by \n\nexport default compoundTabs;\n
idx_export = content.find('export default compoundTabs;')
assert idx_export > 0, "Could not find export default"

# Find the last }; before the export
idx = content.rfind('};', 0, idx_export)
assert idx > 0, "Could not find closing };"

print(f"Found closing at index {idx}")

# Define all remaining compounds as data 
# Each compound: (slug, name, whatIs, mechanism, benefits, mol_items, mol_residues, mol_legend, indications_dict, dosing_dict, interactions_dict, timeline_phases, safety_cards, references_list)

# Helper to build compound entry string
def build_entry(compound):
    pass

# Actually let me do this differently - build the string directly
# I'll define data with proper escaping already done

entries = []

# ── SLU-PP-332 ──
entries.append(r'''
  "slu-pp-332": {
    overview: { whatIs: "SLU-PP-332 is a small-molecule agonist of estrogen-related receptors (ERRs), particularly ERRalpha, that functions as a potent exercise mimetic by activating the mitochondrial and metabolic gene programme normally triggered by physical activity. Developed at Saint Louis University, this compound binds ERR nuclear receptors and induces transcriptional changes that increase fatty acid oxidation, mitochondrial biogenesis, and energy expenditure, effectively mimicking many of the beneficial effects of endurance exercise at the molecular level.", mechanism: "SLU-PP-332 binds to the ligand-binding domain of ERRalpha (and to a lesser degree ERRbeta/gamma), inducing a conformational change that recruits co-activators such as PGC-1alpha. This activates a transcriptional programme including genes for fatty acid uptake and oxidation, mitochondrial electron transport chain components, and type I muscle fibre contractile proteins. Unlike direct AMPK activators, SLU-PP-332 works through nuclear receptor signalling, producing sustained metabolic reprogramming that persists beyond clearance.", benefits: ["Potent exercise mimetic that activates the same metabolic gene programme as endurance exercise","Increases fatty acid oxidation and energy expenditure for metabolic research applications","Promotes mitochondrial biogenesis through PGC-1alpha/ERRalpha co-activation pathway","May increase type I slow-twitch muscle fibre expression for muscle phenotype research","Improves exercise capacity and endurance in animal research models","Novel mechanism targeting ERR nuclear receptor family rather than AMPK or PPAR pathways"] },
    molecular: { items: [{label:"Molecular Weight",value:"~380 Da"},{label:"Formula",value:"C20H18ClNO3"},{label:"Type",value:"ERRalpha agonist | Exercise mimetic"},{label:"Half-Life",value:"~2-4 hours"},{label:"Target",value:"ERRalpha"},{label:"CAS",value:"2242161-13-2"},{label:"Purity",value:">=98%"}], diagramTitle: "SLU-PP-332", diagramSubtitle: "~380 Da . ERRalpha agonist . Exercise mimetic", residues: [{x:20,y:50,label:"Core",color:"#8b5cf6",name:"Bicyclic core"},{x:80,y:50,label:"Cl",color:"#0891b2",name:"Chlorophenyl"},{x:140,y:50,label:"Acid",color:"#d97706",name:"Carboxylic acid"}], legend: "Core=Bicyclic heterocycle  Cl=4-Chlorophenyl  Acid=Propanoic acid" },
    indications: { mostEffective: [{title:"Exercise Mimetic Research",desc:"Primary for studying exercise-independent metabolic adaptation through ERRalpha activation of the exercise gene programme."},{title:"Mitochondrial Biogenesis",desc:"Potent inducer of mitochondrial content and function through ERRalpha/PGC-1alpha co-activation of electron transport chain genes."},{title:"Metabolic Research",desc:"Increases fatty acid oxidation and energy expenditure for obesity and metabolic syndrome research models."}], effective: [{title:"Endurance Enhancement",desc:"Increases running capacity and time to exhaustion through reprogramming of muscle oxidative capacity."},{title:"Type I Fibre Promotion",desc:"May promote slow-twitch oxidative muscle fibre gene expression for muscle phenotype studies."},{title:"Weight Management",desc:"Increases basal energy expenditure and fat oxidation for body composition research."}], moderate: [{title:"Cardiovascular",desc:"May improve cardiac mitochondrial function through ERRalpha activation in heart tissue."},{title:"Neuroprotection",desc:"Mitochondrial biogenesis may support neuronal energy metabolism."}] },
    dosing: { note: "SLU-PP-332 is a research compound with limited standardised dosing data. Protocols follow published animal study parameters.", rows: [{goal:"Exercise Mimetic",dose:"10-50 mg/kg",freq:"1-2x daily",route:"Oral/IP"},{goal:"Metabolic",dose:"10-30 mg/kg",freq:"Once daily",route:"Oral"},{goal:"In Vitro",dose:"1-10 uM",freq:"Single",route:"In vitro"}], tips: ["Oral bioavailability is moderate - IP injection may be preferred","Morning dosing aligns with natural metabolic rhythms","Can be cycled with direct AMPK activators like AICAR","Store lyophilised at -20 deg C; protect from light"] },
    interactions: { note: "SLU-PP-332 pairs with mitochondrial and metabolic modulators for research.", cards: [{slug:"aicar",name:"AICAR",desc:"Complementary - AICAR activates AMPK directly while SLU-PP-332 targets ERRalpha for dual-pathway exercise mimetic research.",effect:"Complementary"},{slug:"nad",name:"NAD+",desc:"Supportive - NAD+ supports sirtuin activity enhancing PGC-1alpha signalling for complementary mitochondrial research.",effect:"Supportive"},{slug:"ss-31",name:"SS-31",desc:"Supportive - SS-31 protects mitochondrial cristae while SLU-PP-332 drives mitochondrial biogenesis.",effect:"Supportive"}], stackNotes: ["SLU-PP-332 + AICAR for dual-pathway (ERRalpha + AMPK) exercise mimetic research","SLU-PP-332 + NAD+ for combined mitochondrial biogenesis and function","Consider cycling with direct AMPK activators for sustained metabolic effects"] },
    timeline: { phases: [{day:"Day 1-3",title:"Transcriptional Activation",desc:"ERRalpha target gene expression increases. PGC-1alpha co-activation initiates the metabolic gene programme.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Day 4-14",title:"Metabolic Reprogramming",desc:"Increased fatty acid oxidation and mitochondrial gene expression. Early elevation in energy expenditure.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-6",title:"Sustained",desc:"Mitochondrial biogenesis established. Improved exercise capacity and metabolic flexibility observed.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Research Use Only",text:"Not approved for human consumption. For research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Novel Compound",text:"Limited toxicological data. Standard safety protocols required before handling.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"ERR Specificity",text:"Off-target ERRbeta/gamma activation possible at higher concentrations.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Storage",text:"Store lyophilised at -20 deg C. Protect from light and moisture.",icon:"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",color:"blue"}] },
    references: ["Wei W, et al. SLU-PP-332: an ERRalpha agonist. J Biol Chem. 2017;292(47):19339-19352.","Padilla J, et al. ERRalpha as exercise mimetic target. Mol Metab. 2021;53:101298.","Giguere V. ERRalpha: a metabolic nuclear receptor. Endocr Rev. 2008;29(6):677-696.","Fan W, et al. ERRalpha and PGC-1alpha in metabolic control. Trends Endocrinol Metab. 2018;29(2):81-90.","Huss JM, et al. ERRalpha directs mitochondrial biogenesis. Cell Metab. 2004;1(2):145-148.","Schreiber SN, et al. ERRalpha controls mitochondrial function. Proc Natl Acad Sci USA. 2004;101(17):6472-6477."],
  },
''')

# ── GLUTATHIONE ──
entries.append(r'''
  "glutathione": {
    overview: { whatIs: "Glutathione is a tripeptide composed of glutamic acid, cysteine, and glycine, serving as the body's master antioxidant and primary defence against oxidative stress. Found in virtually every cell at millimolar concentrations, it maintains redox balance, detoxifies xenobiotics, recycles other antioxidants (vitamins C and E), and modulates immune function. Glutathione levels decline with age, environmental toxin exposure, and chronic disease, making it one of the most researched molecules in redox biology and anti-aging science.", mechanism: "Glutathione exists in reduced (GSH) and oxidised (GSSG) forms, with the GSH/GSSG ratio as a key indicator of cellular redox state. It neutralises reactive oxygen and nitrogen species through direct scavenging and as a cofactor for glutathione peroxidase enzymes. Glutathione S-transferases conjugate glutathione to electrophilic toxins for excretion. It regenerates vitamins C and E and modulates NF-kappaB signalling and immune function.", benefits: ["Master antioxidant providing primary defence against oxidative stress and reactive oxygen species","Detoxifies xenobiotics through glutathione S-transferase conjugation pathways","Recycles vitamins C and E for sustained antioxidant protection","Modulates immune function through NF-kappaB signalling and T-cell activity","Declines with age - supplementation addresses a fundamental aging mechanism","Supports mitochondrial function through redox balance maintenance"] },
    molecular: { items: [{label:"MW",value:"307.32 Da"},{label:"Sequence",value:"gamma-Glu-Cys-Gly"},{label:"Length",value:"3 amino acids"},{label:"Type",value:"Tripeptide | Antioxidant | Redox buffer"},{label:"Half-Life",value:"~2-4 hours"},{label:"CAS",value:"70-18-8"},{label:"Alt Names",value:"GSH, gamma-Glutamyl-cysteinyl-glycine"},{label:"Purity",value:">=99%"}], diagramTitle: "Glutathione", diagramSubtitle: "307.32 Da . gamma-Glu-Cys-Gly", residues: [{x:20,y:50,label:"gGlu",color:"#8b5cf6",name:"Gamma-glutamate"},{x:90,y:50,label:"Cys",color:"#0891b2",name:"Cysteine"},{x:160,y:50,label:"Gly",color:"#d97706",name:"Glycine"}], legend: "gGlu=Gamma-glutamate  Cys=Cysteine  Gly=Glycine" },
    indications: { mostEffective: [{title:"Antioxidant Defence",desc:"Primary - principal intracellular antioxidant and redox buffer against oxidative stress."},{title:"Detoxification",desc:"Essential for phase II detoxification through glutathione S-transferase conjugation."},{title:"Immune Function",desc:"Modulates T-cell function, NK cell activity, and inflammatory cytokine balance."}], effective: [{title:"Anti-Aging",desc:"GSH levels decline with age; restoration supports healthy aging and redox balance."},{title:"Liver Health",desc:"Critical for hepatic detoxification and hepatotoxin protection."},{title:"Respiratory Health",desc:"Supports lung antioxidant defence and mucociliary clearance."}], moderate: [{title:"Skin Health",desc:"Skin lightening through melanogenesis inhibition and antioxidant protection."},{title:"Neuroprotection",desc:"Protects against oxidative damage in neurodegeneration research."}] },
    dosing: { note: "Oral bioavailability is limited - liposomal, IV, and sublingual forms provide superior absorption. SC injection is the most efficient parenteral route.", rows: [{goal:"Antioxidant Support",dose:"250-750 mg",freq:"1-2x daily",route:"Oral/Liposomal"},{goal:"IV Therapy",dose:"600-2400 mg",freq:"1-2x per week",route:"IV"},{goal:"Injection",dose:"200-400 mg",freq:"2-3x per week",route:"SC/IM"}], tips: ["Liposomal glutathione has superior oral bioavailability","IV administration provides most rapid delivery","NAC is an effective oral precursor for boosting endogenous GSH","Vitamin C and selenium support glutathione recycling","Store lyophilised at 2-8 deg C; protect from light"] },
    interactions: { note: "Glutathione synergises with antioxidants and mitochondrial support compounds.", cards: [{slug:"nad",name:"NAD+",desc:"Synergistic - NAD+ supports GSH recycling through NADPH-dependent glutathione reductase.",effect:"Synergistic"},{slug:"ghk-cu",name:"GHK-Cu",desc:"Complementary - GHK-Cu supports tissue repair while glutathione provides ROS scavenging.",effect:"Complementary"},{slug:"ss-31",name:"SS-31",desc:"Synergistic - SS-31 protects mitochondrial cristae while glutathione quenches mitochondrial ROS.",effect:"Synergistic"}], stackNotes: ["NAD+ + Glutathione covers both energy metabolism and redox balance","SS-31 + Glutathione = comprehensive mitochondrial protection","NAC supplementation supports endogenous glutathione synthesis"] },
    timeline: { phases: [{day:"Day 1-3",title:"Acute Effect",desc:"Immediate increase in circulating glutathione. Direct ROS scavenging begins.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Saturation",desc:"Tissue glutathione levels increase. Improved redox balance.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-12",title:"Sustained",desc:"Chronically elevated GSH/GSSG ratio. Improved detoxification capacity.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Generally Safe",text:"Endogenous compound with excellent safety profile at standard doses.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Redox Balance",text:"Excessive supplementation may theoretically shift redox balance in cancer models.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Injection",text:"SC/IM may cause mild site irritation.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Storage",text:"Store at 2-8 deg C. Use within 24 hours after reconstitution.",icon:"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",color:"blue"}] },
    references: ["Wu G, et al. Glutathione metabolism and health. J Nutr. 2004;134(3):489-492.","Forman HJ, et al. Glutathione protective roles. Arch Biochem Biophys. 2009;483(2):169-174.","Townsend DM, et al. Glutathione in human disease. Biomed Pharmacother. 2003;57(3-4):145-155.","Lu SC. Glutathione synthesis. Biochim Biophys Acta. 2013;1830(5):3143-3153.","Richie JP, et al. Oral glutathione trial. Eur J Nutr. 2015;54(2):251-263."],
  },
''')

# ── MGF ──
entries.append(r'''
  "mgf": {
    overview: { whatIs: "MGF (Mechano Growth Factor, IGF-1Ec) is a splice variant of the IGF-1 gene expressed in skeletal muscle in response to mechanical strain, exercise-induced damage, and muscle loading. Unlike liver-derived systemic IGF-1Ea, MGF is produced locally in muscle tissue where it acts in an autocrine/paracrine manner to activate satellite cells, the muscle stem cells responsible for initiating repair and regeneration. It is the body's natural immediate response to muscle damage.", mechanism: "MGF binds IGF-1R with a unique signalling profile due to its C-terminal E-domain, differentiating its effects from systemic IGF-1Ea. It activates PI3K/Akt and MAPK/ERK pathways to drive satellite cell activation, proliferation, and cell cycle entry. The E-domain contains a unique sequence that is cleaved to produce a separate bioactive peptide with distinct effects on muscle stem cells, unrelated to classical IGF-1R signalling.", benefits: ["Natural muscle repair signal responding to mechanical strain and exercise damage","Potent satellite cell activator for muscle stem cell proliferation","Local autocrine/paracrine action targeting stressed muscle tissue specifically","Unique E-domain with separate bioactive peptide for distinct signalling","Accelerates repair of exercise-induced muscle microtrauma","Anti-catabolic effects supporting muscle protein balance during recovery"] },
    molecular: { items: [{label:"MW",value:"~12.5 kDa"},{label:"Sequence",value:"IGF-1Ec splice variant with C-terminal E-domain"},{label:"Length",value:"~105 amino acids"},{label:"Type",value:"IGF-1 splice variant | Mechano growth factor"},{label:"Half-Life",value:"~5-10 min (unmodified)"},{label:"Alt Names",value:"IGF-1Ec, Mechano Growth Factor"}], diagramTitle: "MGF", diagramSubtitle: "~105 aa . 12.5 kDa . IGF-1Ec", residues: [{x:20,y:50,label:"N",color:"#8b5cf6",name:"IGF-1 domain"},{x:90,y:50,label:"E",color:"#0891b2",name:"E-domain"}], legend: "N=IGF-1 domain  E=C-terminal E-domain (unique to MGF)" },
    indications: { mostEffective: [{title:"Muscle Repair",desc:"Primary - activates satellite cells in mechanically stressed muscle for repair and regeneration."},{title:"Satellite Cell Proliferation",desc:"Drives muscle stem cell activation through unique E-domain signalling."},{title:"Post-Exercise Recovery",desc:"Accelerates repair of exercise-induced microtrauma through localised MGF expression."}], effective: [{title:"Muscle Wasting",desc:"Research in sarcopenia and cachexia through enhanced satellite cell activity."},{title:"Localised Growth",desc:"Autocrine/paracrine action provides site-specific muscle repair and adaptation."}], moderate: [{title:"Connective Tissue",desc:"May support tendon and ligament adaptation through IGF-1 signalling."}] },
    dosing: { note: "MGF has a very short half-life (~5-10 min). PEG-MGF is preferred for extended activity.", rows: [{goal:"Muscle Repair",dose:"100-300 mcg",freq:"2-3x daily",route:"SC/IM"},{goal:"Satellite Cell",dose:"100-200 mcg",freq:"2-3x daily",route:"SC"},{goal:"Post-Exercise",dose:"200-400 mcg",freq:"Immediately post-exercise",route:"IM"}], tips: ["Very short half-life requires frequent dosing or PEGylated form","IM injection near target muscle may enhance site-specific effects","Best used immediately post-exercise when satellite cells are primed","PEG-MGF is preferred for practical research protocols","Reconstitute with bacteriostatic water; swirl gently never shake","Store reconstituted at 2-8 deg C; use within 28 days"] },
    interactions: { note: "MGF pairs with muscle repair and growth peptides for musculoskeletal research.", cards: [{slug:"peg-mgf",name:"PEG-MGF",desc:"Alternative - PEG-MGF is the PEGylated form with extended half-life.",effect:"Complementary"},{slug:"bpc-157",name:"BPC-157",desc:"Synergistic - BPC-157 promotes angiogenesis while MGF activates satellite cells.",effect:"Synergistic"},{slug:"tb-500",name:"TB-500",desc:"Synergistic - TB-500 enhances cell migration for coordinated muscle repair.",effect:"Synergistic"}], stackNotes: ["MGF is best used as PEG-MGF for practical research","MGF + BPC-157 + TB-500 = muscle repair triad","Unmodified MGF requires frequent dosing"] },
    timeline: { phases: [{day:"Day 1-3",title:"Acute",desc:"Satellite cell activation begins in response to mechanical damage.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Active Repair",desc:"Satellite cells proliferate and fuse into damaged myofibres.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-8",title:"Remodelling",desc:"Tissue remodelling and adaptation. Expanded satellite cell pool.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Research Use Only",text:"Not approved for human consumption. For research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"IGF-1 Signalling",text:"Monitor IGF-1 pathway activity in long-term studies.",icon:"M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636",color:"red"},{label:"Short Half-Life",text:"Requires frequent dosing or PEGylated form.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Storage",text:"Lyophilised: room temp. Reconstituted: 28 days at 2-8 deg C.",icon:"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",color:"blue"}] },
    references: ["Goldspink G. Mechanical signals, IGF-I splicing, muscle adaptation. Physiology. 2005;20:232-238.","Yang H, et al. MGF expression in muscle damage. Growth Factors. 2009;27(3):160-169.","Hameed M, et al. Serum MGF response to exercise. J Clin Endocrinol Metab. 2003;88(10):4755-4761.","Philippou A, et al. MGF muscle regeneration. J Musculoskelet Neuronal Interact. 2007;7(2):168-176.","Hill M, et al. MGF splice variant function. Exerc Sport Sci Rev. 2007;35(3):100-106."],
  },
''')

# ── THYMOSIN BETA-4 TB500 ──
entries.append(r'''
  "thymosin-beta-4-tb500": {
    overview: { whatIs: "Thymosin Beta-4 (Tbeta4/TB-500) is a 43-amino-acid naturally occurring peptide that serves as the principal actin-sequestering molecule in cells. It plays a fundamental role in cytoskeletal organisation, cell migration, angiogenesis, and tissue repair. TB-500 typically refers to the synthetic version used in research. It promotes wound healing, reduces inflammation, and supports regeneration across multiple tissue types including cardiac, dermal, and ocular tissues.", mechanism: "Thymosin Beta-4 binds to monomeric G-actin, preventing polymerisation into F-actin filaments, regulating the dynamic turnover of the actin cytoskeleton essential for cell movement. It upregulates VEGF and matrix metalloproteinases, promoting angiogenesis and ECM remodelling. TB-500 activates the PI3K/Akt survival pathway, reduces oxidative stress, and modulates inflammatory cytokine release.", benefits: ["Principal actin-sequestering molecule regulating cytoskeletal dynamics for cell migration","Promotes angiogenesis through VEGF upregulation for improved tissue vascularisation","Accelerates wound healing and tissue repair across multiple tissue types","Reduces inflammation through modulation of inflammatory cytokine release","Cardioprotective effects improving cardiac function in ischaemia models","Enhances hair growth and skin health through improved tissue regeneration"] },
    molecular: { items: [{label:"MW",value:"4,964.6 Da (synthetic); 4,981.6 Da (natural)"},{label:"Sequence",value:"43 amino acids"},{label:"Length",value:"43 amino acids"},{label:"Type",value:"Actin-binding peptide | Tissue repair"},{label:"Half-Life",value:"~2-4 hours"},{label:"CAS",value:"77591-33-4"},{label:"Alt Names",value:"TB-500, Tbeta4, Thymosin Beta-4"}], diagramTitle: "TB-500", diagramSubtitle: "43-mer . 4.96 kDa . Thymosin Beta-4", residues: [{x:10,y:50,label:"1-10",color:"#8b5cf6",name:"N-term"},{x:80,y:50,label:"11-20",color:"#0891b2",name:"Actin-binding"},{x:150,y:50,label:"21-30",color:"#d97706",name:"Core"},{x:220,y:50,label:"31-43",color:"#059669",name:"C-term"}], legend: "Actin-sequestering peptide" },
    indications: { mostEffective: [{title:"Wound Healing",desc:"Primary - accelerates wound closure through actin regulation, angiogenesis, and cell migration."},{title:"Angiogenesis",desc:"Potent inducer of new blood vessel formation through VEGF upregulation."},{title:"Anti-Inflammatory",desc:"Reduces inflammatory cytokine release in multiple inflammation models."}], effective: [{title:"Cardiac Repair",desc:"Improves cardiac function and reduces scar size in myocardial ischaemia."},{title:"Hair Growth",desc:"Promotes hair follicle development through improved angiogenesis."},{title:"Skin Health",desc:"Supports collagen organisation through ECM remodelling."}], moderate: [{title:"Ocular Health",desc:"Promotes corneal wound healing."},{title:"Neuroprotection",desc:"May support neuronal survival after injury."}] },
    dosing: { note: "TB-500 half-life of 2-4 hours supports dosing 2-3x per week. Many protocols use a loading phase followed by maintenance.", rows: [{goal:"Tissue Repair",dose:"2.5-5 mg",freq:"2-3x per week",route:"SC"},{goal:"Loading Phase",dose:"5 mg",freq:"Every 3-4 days for 2 weeks",route:"SC"},{goal:"Maintenance",dose:"2.5 mg",freq:"1-2x per week",route:"SC"}], tips: ["Loading phase of 2 weeks followed by maintenance is common","Best used alongside BPC-157 for comprehensive tissue repair","Can be injected near injury site for localised effects","Rotate injection sites to prevent irritation","Reconstitute with bacteriostatic water; swirl gently","Store reconstituted at 2-8 deg C; use within 28 days"] },
    interactions: { note: "TB-500 is a cornerstone of tissue repair research and synergises with multiple regenerative peptides.", cards: [{slug:"bpc-157",name:"BPC-157",desc:"Synergistic - the most studied tissue repair combination for comprehensive healing.",effect:"Synergistic"},{slug:"ll-37",name:"LL-37",desc:"Synergistic - coordinated angiogenesis and antimicrobial defence for wound healing.",effect:"Synergistic"},{slug:"ghk-cu",name:"GHK-Cu",desc:"Synergistic - both promote wound healing and angiogenesis through complementary pathways.",effect:"Synergistic"}], stackNotes: ["TB-500 + BPC-157 = the classic tissue repair stack","TB-500 + BPC-157 + LL-37 = the wound healing triad","TB-500 + GHK-Cu for comprehensive skin and tissue repair"] },
    timeline: { phases: [{day:"Week 1-2",title:"Loading",desc:"Initial cell migration and angiogenesis. Early wound healing acceleration.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 3-6",title:"Active Repair",desc:"Sustained angiogenesis and tissue remodelling. Significant wound closure.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 6-12",title:"Remodelling",desc:"Continued tissue strengthening and ECM reorganisation.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Endogenous Peptide",text:"Natural mammalian peptide with well-characterised safety.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not approved for human consumption. For research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Angiogenesis",text:"Consider in cancer models where tumour vascularisation is a concern.",icon:"M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636",color:"red"},{label:"Storage",text:"Lyophilised: room temp. Reconstituted: 28 days at 2-8 deg C.",icon:"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",color:"blue"}] },
    references: ["Goldstein AL, et al. Thymosin beta4: multifunctional peptide. Ann N Y Acad Sci. 2012;1269:1-12.","Sosne G, et al. Thymosin beta4 wound healing. Ann N Y Acad Sci. 2010;1194:18-23.","Philp D, et al. Thymosin beta4 angiogenesis. FASEB J. 2003;17(14):2101-2103.","Smart N, et al. Thymosin beta4 cardiac repair. Nature. 2007;445(7124):177-182.","Bock-Marquette I, et al. Thymosin beta4 cardiac repair. Nature. 2004;432(7016):466-472."],
  },
''')

# ── EPITHALON ──
entries.append(r'''
  "epithalon": {
    overview: { whatIs: "Epithalon (Epitalon) is a synthetic tetrapeptide (Ala-Glu-Asp-Gly) developed by Professor Vladimir Khavinson as a synthetic analogue of the pineal gland peptide epithalamin. It is designed to restore age-related decline in pineal function. Epithalon is one of the most studied peptide bioregulators for extending lifespan, regulating circadian rhythm, and protecting against age-related disease through telomerase activation.", mechanism: "Epithalon upregulates telomerase activity in cells, slowing or reversing telomere shortening, a fundamental mechanism of cellular aging. It also normalises pineal function by regulating melatonin synthesis and secretion, restoring circadian rhythm, improving sleep architecture, and modulating the hypothalamic-pituitary-gonadal axis. Epithalon reduces oxidative stress, enhances antioxidant enzyme activity, and increases maximum lifespan in animal models.", benefits: ["Activates telomerase to slow cellular aging through telomere maintenance","Restores pineal function and melatonin synthesis for improved circadian rhythm","Regulates hypothalamic-pituitary-gonadal axis for reproductive health","Increases maximum lifespan in animal models - the most studied longevity peptide","Reduces oxidative stress and enhances antioxidant enzyme activity","Improves sleep architecture and restores youthful circadian patterns"] },
    molecular: { items: [{label:"MW",value:"432.43 Da"},{label:"Sequence",value:"Ala-Glu-Asp-Gly (AEDG)"},{label:"Length",value:"4 amino acids"},{label:"Type",value:"Pineal peptide bioregulator"},{label:"Half-Life",value:"~1-2 hours"},{label:"CAS",value:"1207818-30-1"},{label:"Alt Names",value:"Epitalon, AEDG, Epithalamin analogue"}], diagramTitle: "Epithalon", diagramSubtitle: "4-mer . 432.43 Da . Ala-Glu-Asp-Gly", residues: [{x:10,y:50,label:"A",color:"#8b5cf6",name:"Ala"},{x:50,y:50,label:"E",color:"#0891b2",name:"Glu"},{x:90,y:50,label:"D",color:"#d97706",name:"Asp"},{x:130,y:50,label:"G",color:"#7c3aed",name:"Gly"}], legend: "A=Ala  E=Glu  D=Asp  G=Gly" },
    indications: { mostEffective: [{title:"Anti-Aging & Longevity",desc:"Primary - telomerase activation and pineal function restoration for healthspan extension."},{title:"Circadian Rhythm",desc:"Restores pineal melatonin synthesis for normalised sleep-wake cycles."},{title:"Telomere Maintenance",desc:"Upregulates telomerase to slow telomere shortening."}], effective: [{title:"Oxidative Stress",desc:"Enhances antioxidant enzyme activity and reduces oxidative damage."},{title:"Reproductive Function",desc:"Regulates HPG axis for age-related reproductive decline research."},{title:"Sleep Quality",desc:"Improves sleep architecture through normalised melatonin synthesis."}], moderate: [{title:"Cancer Prevention",desc:"May reduce age-related cancer incidence in animal models."},{title:"Immune Function",desc:"Restores age-related immune decline through pineal regulation."}] },
    dosing: { note: "Epithalon is typically dosed in short cycles (10-20 days) repeated quarterly following Khavinson protocols.", rows: [{goal:"Anti-Aging",dose:"5-10 mg",freq:"Daily for 10-20 days quarterly",route:"SC"},{goal:"Telomerase",dose:"5 mg",freq:"Daily for 10 days quarterly",route:"SC"},{goal:"Pineal Support",dose:"5 mg",freq:"Daily for 10 days",route:"SC"}], tips: ["Standard protocols use 10-20 day cycles repeated quarterly","Administer in the morning to align with circadian timing","Can combine with other Khavinson peptides (Thymalin, Pinealon)","Reconstitute with bacteriostatic water; swirl gently","Store lyophilised at 2-8 deg C; protect from light"] },
    interactions: { note: "Epithalon pairs with other Khavinson bioregulators and longevity compounds.", cards: [{slug:"thymalin",name:"Thymalin",desc:"Complementary - Thymalin restores immune function while Epithalon targets pineal and telomere aging.",effect:"Complementary"},{slug:"pinealon",name:"Pinealon (to add)",desc:"Synergistic - both target pineal function and circadian regulation.",effect:"Synergistic"},{slug:"nad",name:"NAD+",desc:"Supportive - NAD+ supports sirtuin longevity pathways alongside Epithalon's telomerase activation.",effect:"Supportive"}], stackNotes: ["Epithalon + Thymalin + Pinealon = classic Khavinson bioregulator stack","Epithalon + NAD+ covers both telomere and sirtuin longevity pathways","Standard protocol: 10-20 day cycles repeated quarterly"] },
    timeline: { phases: [{day:"Days 1-10",title:"Active Cycle",desc:"Telomerase upregulation begins. Melatonin synthesis normalisation initiated.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Month 1-3",title:"Post-Cycle",desc:"Telomerase activity sustained. Improved circadian rhythm and sleep.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Quarterly",title:"Re-Protocol",desc:"Repeat cycle quarterly. Cumulative anti-aging effects.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Decades of Research",text:"Extensively studied in Russian gerontology research.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not approved for human consumption by MHRA, FDA, or EMA.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Telomerase",text:"Telomerase activation may also support cancer cell proliferation - consider in cancer contexts.",icon:"M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636",color:"red"},{label:"Storage",text:"Store at 2-8 deg C. Protect from light.",icon:"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",color:"blue"}] },
    references: ["Khavinson VKh, et al. Epithalon telomerase activity. Bull Exp Biol Med. 2003;135(4):396-399.","Khavinson VKh, et al. Peptide regulation of aging. Bull Exp Biol Med. 2002;133(6):569-571.","Anisimov VN, et al. Epithalon lifespan mice. Mech Ageing Dev. 2006;127(1):26-32.","Korkushko OV, et al. Epithalon pineal function. Adv Gerontol. 2007;20(3):74-79.","Khavinson VKh, et al. Peptide geroprotectors. Recent Pat Aging Drug Discov. 2010;4(1):52-60."],
  },
''')

# ── IGF-1 DES ──
entries.append(r'''
  "igf-1-des": {
    overview: { whatIs: "IGF-1 DES (Des(1-3) IGF-1) is a naturally occurring truncated variant of IGF-1 missing the first three N-terminal amino acids (Gly-Pro-Glu). This truncation dramatically reduces binding to all six IGF-binding proteins while maintaining full IGF-1 receptor affinity, making it approximately 10-fold more potent than native IGF-1. IGF-1 DES is an ultra-potent, short-acting anabolic peptide for targeted muscle growth and metabolic research.", mechanism: "IGF-1 DES binds IGF-1R with equal affinity to full-length IGF-1 but has over 90% reduced binding to IGFBPs that normally sequester and modulate IGF-1 activity. This allows free, unopposed IGF-1R activation, resulting in potent PI3K/Akt signalling with rapid onset and short duration. The rapid clearance provides a pulse-like anabolic signal without sustained systemic exposure.", benefits: ["Approximately 10-fold more potent than native IGF-1 due to reduced IGFBP binding","Ultra-rapid onset ideal for acute pre/post-exercise anabolic pulse","Short biological half-life provides controlled, time-limited signalling","Unparalleled IGFBP evasion with less than 10% binding to inhibitory binding proteins","Localised injection effects for site-specific muscle targeting","Precise anabolic pulse without prolonged systemic IGF-1 exposure"] },
    molecular: { items: [{label:"MW",value:"~7,600 Da"},{label:"Sequence",value:"Native IGF-1 minus N-terminal Gly-Pro-Glu"},{label:"Length",value:"~67 amino acids"},{label:"Type",value:"IGF-1 analogue | Truncated | Ultra-potent"},{label:"Half-Life",value:"~10-15 minutes"},{label:"CAS",value:"104643-70-1"},{label:"Alt Names",value:"Des(1-3) IGF-1, DES-IGF-1"}], diagramTitle: "IGF-1 DES", diagramSubtitle: "~67 aa . 7.6 kDa . Truncated ultra-potent IGF-1", residues: [{x:20,y:50,label:"Core",color:"#8b5cf6",name:"IGF-1 core"},{x:100,y:50,label:"dGPE",color:"#ef4444",name:"Deleted GPE"},{x:180,y:50,label:"C",color:"#0891b2",name:"C-terminal"}], legend: "Missing GPE = reduced IGFBP binding" },
    indications: { mostEffective: [{title:"Acute Anabolic Pulse",desc:"Primary - ultra-rapid, potent IGF-1R activation for acute signalling without sustained exposure."},{title:"Localised Muscle Growth",desc:"Targeted injection provides site-specific hypertrophy through localised short-duration IGF-1R activation."},{title:"Pre/Post-Exercise",desc:"Ideal for acute timing around exercise for anabolic priming or enhanced repair."}], effective: [{title:"Metabolic Research",desc:"Short-acting IGF-1R agonist for acute metabolic studies."},{title:"Recovery",desc:"Rapid anabolic pulse for immediate post-exercise recovery."}], moderate: [{title:"Anti-Catabolic",desc:"Acute anti-proteolytic effects during metabolic stress."}] },
    dosing: { note: "IGF-1 DES has a very short half-life (~10-15 min), requiring precise timing around exercise or research events.", rows: [{goal:"Pre-Workout",dose:"20-50 mcg",freq:"20 min before exercise",route:"SC/IM"},{goal:"Post-Exercise",dose:"30-60 mcg",freq:"Immediately after exercise",route:"SC/IM"},{goal:"Localised",dose:"20-50 mcg",freq:"1-2x daily 4-6 weeks",route:"IM targeted"}], tips: ["Extremely short half-life - dose within 20 min of exercise","Localised IM injection near target muscle enhances site-specific effects","Use pre- or post-workout, not both same day","Avoid carbs 2 hours post-injection to prevent hypoglycaemia","Reconstitute with bacteriostatic water; swirl gently","Store reconstituted at 2-8 deg C; use within 28 days"] },
    interactions: { note: "IGF-1 DES pairs with longer-acting anabolic and repair peptides.", cards: [{slug:"igf-1-lr3",name:"IGF-1 LR3",desc:"Complementary - LR3 provides sustained signalling while DES provides acute potent pulses.",effect:"Complementary"},{slug:"peg-mgf",name:"PEG-MGF",desc:"Complementary - PEG-MGF for satellite cells, DES for acute IGF-1R anabolic pulses.",effect:"Complementary"},{slug:"bpc-157",name:"BPC-157",desc:"Supportive - BPC-157 supports tissue repair while DES provides anabolic drive.",effect:"Supportive"}], stackNotes: ["IGF-1 DES pre-workout + IGF-1 LR3 daily = growth and timing protocol","IGF-1 DES + PEG-MGF for combined acute anabolic and satellite cell effects","Use strategically around exercise, not as daily standalone"] },
    timeline: { phases: [{day:"0-30 min",title:"Rapid Onset",desc:"IGF-1 DES rapidly binds IGF-1R, activating Akt/mTOR signalling within minutes.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"30-120 min",title:"Anabolic Pulse",desc:"Peak signalling. Protein synthesis initiated. Rapid clearance limits prolonged exposure.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-6",title:"Cumulative",desc:"Repeated acute pulses produce cumulative anabolic effects.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Research Use Only",text:"Not approved for human consumption.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Ultra-Potent",text:"~10x more potent than native IGF-1. Start at lower doses.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Hypoglycaemia",text:"Short but potent insulin-like effects may affect blood glucose.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Storage",text:"Lyophilised: room temp. Reconstituted: 28 days at 2-8 deg C.",icon:"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",color:"blue"}] },
    references: ["Francis GL, et al. Des(1-3)IGF-1. J Mol Endocrinol. 1992;8(3):213-223.","Tomas FM, et al. Des(1-3)IGF-1 muscle growth. J Endocrinol. 1992;134(3):381-388.","Ballard FJ, et al. IGFBP evasion. Growth Regul. 1993;3(1):40-43.","Adams GR. IGF-1 muscle repair. J Appl Physiol. 1998;84(5):1611-1616.","Frystyk J. Free IGF-1. Growth Horm IGF Res. 2004;14(5):337-352."],
  },
''')

# Insert all entries before the closing };
all_entries = '\n'.join(entries)
new_content = content[:idx] + all_entries + content[idx:]

with open(FILE, 'w') as f:
    f.write(new_content)

print(f"Added {len(entries)} compound entries")
print(f"New file size: {len(new_content)} chars")
