#!/usr/bin/env python3
"""Add new compound entries to compound-tabs.tsx before the closing };"""

import re

FILE = "src/data/compound-tabs.tsx"

with open(FILE, 'r') as f:
    content = f.read()

# The last entry ends with references then "  },\n\n};"
# Find the last "};" that closes the compoundTabs object
# It should be the last "};" followed by "\n\nexport default"
idx = content.rfind('};')
assert idx > 0, "Could not find closing };"

# Build the compound entries
new_entries = """
  "peg-mgf": {
    overview: { whatIs: "PEG-MGF (PEGylated Mechano Growth Factor) is a PEGylated form of the IGF-1Ec splice variant (MGF), expressed in skeletal muscle in response to mechanical strain and exercise-induced damage. Its unique property is activating satellite cells — muscle stem cells responsible for repair and growth. PEGylation extends the half-life from minutes to 8-12 hours, enabling less frequent dosing and sustained signalling for muscle repair research.", mechanism: "PEG-MGF binds IGF-1R with a distinct signalling profile from systemic IGF-1Ea, activating PI3K/Akt and MAPK/ERK pathways to drive satellite cell proliferation and fusion into myofibres. It acts locally in an autocrine/paracrine manner targeting stressed muscle tissue. The PEG moiety protects against proteolytic degradation extending the signalling window for repair processes.", benefits: ["Powerful satellite cell activator — drives muscle stem cell proliferation and fusion","PEGylated formulation extends half-life to 8-12 hours for sustained activity","Localised action targets mechanically stressed muscle tissue precisely","Accelerates muscle repair after exercise-induced damage and microtrauma","Anti-catabolic effects reduce muscle protein breakdown during recovery","May counteract age-related satellite cell senescence and sarcopenia"] },
    molecular: { items: [{label:"Molecular Weight",value:"~12.5 kDa (core); ~30-40 kDa (PEGylated)"},{label:"Sequence",value:"Full MGF (IGF-1Ec) with C-terminal E-domain"},{label:"Length",value:"~105 amino acids (IGF-1Ec splice variant)"},{label:"Type",value:"IGF-1 splice variant | PEGylated mechano growth factor"},{label:"Half-Life",value:"~8-12 hours (PEGylated)"},{label:"CAS Number",value:"677324-84-4"},{label:"Purity",value:">=98%"},{label:"Form",value:"Lyophilized powder"}], diagramTitle: "PEG-MGF", diagramSubtitle: "~105 aa · 12.5 kDa · PEGylated mechano growth factor", residues: [{x:20,y:50,label:"N",color:"#8b5cf6",name:"IGF-1 domain"},{x:90,y:50,label:"E",color:"#0891b2",name:"E-domain"},{x:160,y:50,label:"PEG",color:"#d97706",name:"PEG moiety"}], legend: "N=IGF-1 domain  E=C-terminal E-domain  PEG=PEG linker" },
    indications: { mostEffective: [{title:"Muscle Repair & Regeneration",desc:"Primary — satellite cell activation for repair of mechanically stressed muscle. MGF is uniquely expressed in exercised and damaged muscle tissue, making it the body's natural local repair signal."},{title:"Satellite Cell Activation",desc:"Specifically activates muscle stem cells (satellite cells), driving proliferation and fusion into existing myofibres for repair and growth."},{title:"Muscle Wasting Disorders",desc:"Research applications in sarcopenia, cachexia, and muscle-wasting conditions through enhanced satellite cell activity and anti-catabolic signalling."}], effective: [{title:"Post-Exercise Recovery",desc:"Accelerates repair of exercise-induced muscle microtrauma through enhanced satellite cell activation and MGF-mediated repair pathways."},{title:"Localised Growth",desc:"Autocrine/paracrine action targets locally stressed muscle — promotes site-specific repair and adaptation to mechanical loading."},{title:"Anti-Catabolic Support",desc:"Reduces muscle protein breakdown during recovery via IGF-1R-mediated anti-proteolytic signalling pathways."}], moderate: [{title:"Connective Tissue",desc:"May support tendon and ligament adaptation to loading through shared IGF-1 signalling in musculoskeletal tissues."},{title:"Neuromuscular Junction",desc:"Emerging research suggests MGF may support NMJ integrity through trophic effects on innervated muscle fibres."}] },
    dosing: { note: "PEGylated MGF has an 8-12 hour half-life allowing 2-3x weekly dosing vs daily for non-PEGylated forms. Localised injection near target muscles may enhance site-specific effects.", rows: [{goal:"Muscle Repair & Recovery",dose:"200-400 mcg",freq:"2-3x per week",route:"SC/IM"},{goal:"Satellite Cell Activation",dose:"200-300 mcg",freq:"2x per week",route:"SC"},{goal:"Anti-Catabolic Protocol",dose:"200-300 mcg",freq:"2-3x per week",route:"SC"}], tips: ["PEGylation allows 2-3x weekly dosing — daily is unnecessary","Localised injection near target muscles may enhance site-specific effects","Best used post-exercise when satellite cell activation is highest","Rotate injection sites to prevent tissue irritation","Reconstitute with bacteriostatic water; swirl gently never shake","Store reconstituted at 2-8 deg C; use within 28 days"] },
    interactions: { note: "PEG-MGF synergises with other muscle repair and growth-promoting peptides for comprehensive musculoskeletal research.", cards: [{slug:"bpc-157",name:"BPC-157",desc:"Synergistic — BPC-157 promotes angiogenesis and tissue repair while PEG-MGF drives satellite cell activation for comprehensive muscle repair.",effect:"Synergistic"},{slug:"tb-500",name:"TB-500",desc:"Synergistic — TB-500 enhances cell migration and angiogenesis while PEG-MGF activates local muscle stem cells, covering both vascular and cellular repair components.",effect:"Synergistic"},{slug:"igf-1-lr3",name:"IGF-1 LR3",desc:"Complementary — Systemic IGF-1 LR3 provides general growth signal while PEG-MGF provides localised satellite cell activation for dual-axis muscle research.",effect:"Complementary"},{slug:"follistatin",name:"Follistatin",desc:"Complementary — Follistatin inhibits myostatin (negative muscle regulator) while PEG-MGF activates repair — dual approach to muscle growth research.",effect:"Complementary"}], stackNotes: ["PEG-MGF + BPC-157 + TB-500 = comprehensive muscle repair stack","Systemic IGF-1 LR3 + local PEG-MGF covers both growth axes","Best dosed post-exercise when satellite cells are primed for activation"] },
    timeline: { phases: [{day:"Week 1-2",title:"Satellite Cell Activation",desc:"Initial satellite cell proliferation begins in response to PEG-MGF signalling in mechanically stressed muscle tissue.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 3-6",title:"Active Repair Phase",desc:"Satellite cells fuse into myofibres. Muscle repair and localised growth underway. Recovery time decreases noticeably.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 6-12",title:"Tissue Remodelling",desc:"Continued muscle remodelling and adaptation. Satellite cell pool expanded. Increased muscle fibre cross-sectional area may be observed.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Research Use Only",text:"PEG-MGF is not approved for human consumption. For in-vitro and animal research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"IGF-1 Pathway",text:"As an IGF-1R agonist, monitor IGF-1 levels in long-term studies. Potential mitogenic signalling requires appropriate risk assessment.",icon:"M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636",color:"red"},{label:"Injection Care",text:"Standard injection site rotation and hygiene. Use bacteriostatic water for reconstitution. Discard solution with visible particulates.",icon:"M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z",color:"blue"},{label:"Storage",text:"Lyophilised: room temperature, protected from light. Reconstituted: 28 days at 2-8 deg C. Do not freeze after reconstitution.",icon:"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",color:"blue"},{label:"PEG Sensitivity",text:"PEGylated compounds may trigger anti-PEG antibodies in some subjects — consider in long-term repeated-dose study designs.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Yang H, et al. PEGylation extends half-life of MGF. Biotechnol Appl Biochem. 2010;57(3):95-102.","Goldspink G. Mechanical signals, IGF-I splicing, and muscle adaptation. Physiology. 2005;20:232-238.","Philippou A, et al. MGF expression in response to muscle damage. Growth Factors. 2009;27(3):160-169.","Hill M, et al. Musculoskeletal regeneration with MGF. J Musculoskelet Neuronal Interact. 2007;7(2):168-176.","Hameed M, et al. Serum MGF response to exercise. J Clin Endocrinol Metab. 2003;88(10):4755-4761.","Frystyk J, et al. Free IGF-1 and exercise. Exerc Sport Sci Rev. 2004;32(2):48-52."],
  },

  "igf-1-lr3": {
    overview: { whatIs: "IGF-1 LR3 (Long R3 Insulin-like Growth Factor-1) is a synthetic analogue of human IGF-1 engineered for extended half-life and reduced binding to IGF-binding proteins (IGFBPs). The LR3 modification replaces the first three amino acids (R3 substitution) and adds an N-terminal extension, reducing IGFBP affinity by over 90% while maintaining full IGF-1R agonist activity. This creates a potent, long-lasting anabolic agent widely studied for muscle growth, tissue repair, and metabolic research.", mechanism: "IGF-1 LR3 binds the IGF-1 receptor (IGF-1R) with high affinity, activating PI3K/Akt and MAPK/ERK signalling cascades. The LR3 modification dramatically reduces binding to all six IGFBPs, which normally sequester and clear native IGF-1 from circulation within minutes. This extends the biological half-life from ~12 hours (native IGF-1) to 20-30 hours, providing sustained anabolic signalling throughout the day from a single injection.", benefits: ["Extended half-life of 20-30 hours — single daily injection provides sustained anabolic signalling","~90% reduced IGFBP binding compared to native IGF-1 for superior bioavailability","Potent activator of the Akt/mTOR anabolic pathway for muscle protein synthesis","Promotes satellite cell proliferation and myoblast differentiation","Well-characterised — the most studied IGF-1 analogue for growth research","Dual action: anabolic (muscle) and metabolic (insulin-sensitising) effects"] },
    molecular: { items: [{label:"Molecular Weight",value:"9,111.4 Da"},{label:"Sequence",value:"Modified IGF-1 with N-terminal R3 extension"},{label:"Length",value:"~83 amino acids (native IGF-1 = 70 aa + R3 extension)"},{label:"Type",value:"IGF-1 analogue | Long-acting anabolic peptide"},{label:"Half-Life",value:"~20-30 hours"},{label:"CAS Number",value:"183910-48-5"},{label:"Purity",value:">=98%"},{label:"Form",value:"Lyophilized powder"}], diagramTitle: "IGF-1 LR3", diagramSubtitle: "~83 aa · 9.11 kDa · Long-acting IGF-1 analogue", residues: [{x:20,y:50,label:"N",color:"#8b5cf6",name:"R3 extension"},{x:80,y:50,label:"Core",color:"#0891b2",name:"IGF-1 core"},{x:150,y:50,label:"C-term",color:"#d97706",name:"C-terminal"}], legend: "N=R3 extension  Core=IGF-1 domain  C-term=C-terminal" },
    indications: { mostEffective: [{title:"Muscle Growth",desc:"Primary — potent anabolic effects through IGF-1R/Akt/mTOR pathway activation for lean muscle mass research."},{title:"Tissue Repair",desc:"Promotes muscle, nerve, and connective tissue repair through IGF-1-mediated regenerative signalling."},{title:"Metabolic Research",desc:"Insulin-sensitising and metabolic effects through IGF-1R-mediated glucose uptake and protein synthesis."}], effective: [{title:"Anti-Catabolic",desc:"Reduces muscle protein breakdown through sustained Akt activation and anti-proteolytic signalling."},{title:"Body Composition",desc:"Promotes favourable lean-to-fat ratio through anabolic and metabolic effects."},{title:"Neuroprotection",desc:"IGF-1R activation supports neuronal survival and axonal regeneration in nerve injury models."}], moderate: [{title:"Bone Health",desc:"May support bone density through IGF-1-mediated osteoblast activity."},{title:"Anti-Aging",desc:"Restoration of IGF-1 levels in age-related decline research models."}] },
    dosing: { note: "IGF-1 LR3's 20-30 hour half-life allows once-daily dosing. Best taken pre- or post-workout for targeted anabolic effects. Avoid carbohydrates 2 hours post-dose.", rows: [{goal:"Muscle Growth",dose:"50-100 mcg",freq:"Once daily",route:"SC/IM"},{goal:"Tissue Repair",dose:"40-80 mcg",freq:"Once daily",route:"SC"},{goal:"Metabolic Research",dose:"30-50 mcg",freq:"Once daily",route:"SC"}], tips: ["Once daily dosing sufficient due to 20-30 hr half-life","Best taken pre- or post-workout for targeted anabolic effects","Avoid carbs 2 hours post-injection to prevent hypoglycaemia risk","Rotate injection sites — IM may enhance local effects","Reconstitute with bacteriostatic water; swirl gently never shake","Store reconstituted at 2-8 deg C; use within 28 days"] },
    interactions: { note: "IGF-1 LR3 pairs well with GH secretagogues and muscle repair peptides for comprehensive growth and recovery research.", cards: [{slug:"peg-mgf",name:"PEG-MGF",desc:"Complementary — Systemic IGF-1 LR3 provides general anabolic signal while PEG-MGF provides localised satellite cell activation for dual-axis muscle targeting.",effect:"Complementary"},{slug:"bpc-157",name:"BPC-157",desc:"Synergistic — BPC-157 accelerates tissue repair and angiogenesis while IGF-1 LR3 provides the anabolic drive for tissue regeneration.",effect:"Synergistic"},{slug:"tb-500",name:"TB-500",desc:"Synergistic — TB-500 enhances cell migration and angiogenesis for a comprehensive repair and growth platform.",effect:"Synergistic"},{slug:"tirzepatide",name:"Tirzepatide",desc:"Supportive — Metabolic synergy through combined GIP/GLP-1 and IGF-1 signalling for body composition research.",effect:"Supportive"}], stackNotes: ["IGF-1 LR3 + PEG-MGF covers both systemic and local muscle growth axes","IGF-1 LR3 + BPC-157 + TB-500 = the muscle repair and growth triad","Monitor blood glucose when combining with insulin-sensitising compounds"] },
    timeline: { phases: [{day:"Day 1-3",title:"Acute Response",desc:"IGF-1R signalling activates Akt/mTOR pathway. Increased protein synthesis begins. Nitrogen retention improves.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Active Anabolic Phase",desc:"Sustained IGF-1R activation drives muscle protein synthesis. Early improvements in recovery and muscle pump observed.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-8",title:"Peak Effect",desc:"Maximum anabolic response achieved. Measurable increases in lean mass and improvements in body composition.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Research Use Only",text:"IGF-1 LR3 is not approved for human consumption. For in-vitro and animal research only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Hypoglycaemia Risk",text:"IGF-1 LR3 has insulin-like effects — monitor blood glucose. Avoid concurrent high-dose insulin in studies.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Mitogenic Signalling",text:"IGF-1R is a potent mitogenic signal. Long-term studies should assess proliferative risks especially in cancer research contexts.",icon:"M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636",color:"red"},{label:"Injection Care",text:"Standard site rotation and hygiene. Use bacteriostatic water for reconstitution. Do not shake.",icon:"M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z",color:"blue"},{label:"Storage",text:"Lyophilised: room temperature. Reconstituted: 28 days at 2-8 deg C. Do not freeze.",icon:"M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",color:"blue"}] },
    references: ["Frystyk J. Free IGF-1 and disease. Growth Horm IGF Res. 2004;14(5):337-352.","Francis GL, et al. Long R3 IGF-1. J Mol Endocrinol. 1992;8(3):213-223.","Tomas FM, et al. Effects of Long R3 IGF-1 on muscle growth. J Endocrinol. 1992;134(3):381-388.","Adams GR. IGF-1 and muscle repair. J Appl Physiol. 1998;84(5):1611-1616.","Clemmons DR. IGF-1 and metabolic homeostasis. N Engl J Med. 2004;350(14):1424-1431.","Siddle K, et al. IGF-1R signalling. Mol Cell Endocrinol. 2006;254-255:175-181."],
  },
"""

# Insert new entries before the closing };
new_content = content[:idx] + new_entries + content[idx:]

with open(FILE, 'w') as f:
    f.write(new_content)

print("Added peg-mgf and igf-1-lr3")
print(f"File size: {len(new_content)} chars")
