#!/usr/bin/env python3
"""Add ALL compounds from remaining list in one go using compact format."""
FILE = "src/data/compound-tabs.tsx"
with open(FILE, 'r') as f:
    content = f.read()
idx = content.rfind('};')
assert idx > 0

entries = []

# ── VESUGEN ──
entries.append(r'''
  "vesugen": {
    overview: { whatIs: "Vesugen is a synthetic peptide bioregulator developed by Russian scientist Vladimir Khavinson based on the amino acid sequence of the vascular endothelium. It is designed to restore and maintain healthy blood vessel function by normalising endothelial cell metabolism, improving microcirculation, and supporting vascular health. Vesugen is part of the Khavinson peptide bioregulator system that targets specific organ systems.", mechanism: "Vesugen acts as a tissue-specific bioregulator, normalising gene expression and protein synthesis in vascular endothelial cells. It binds to DNA regulatory sequences to restore age-related decline in endothelial function, promoting nitric oxide production, improving capillary permeability, and supporting angiogenesis.", benefits: ["Restores vascular endothelial function and health","Improves microcirculation and capillary permeability","Supports healthy blood pressure regulation","Promotes angiogenesis for tissue repair","Part of the Khavinson peptide bioregulator system","Age-related vascular decline research applications"] },
    molecular: { items: [{label:"MW",value:"~1,200 Da"},{label:"Sequence",value:"Short peptide (specific sequence proprietary)"},{label:"Type",value:"Vascular peptide bioregulator"},{label:"Half-Life",value:"~1-2 hours"},{label:"Alt Names",value:"Vesugen peptide, Vessel bioregulator"}], diagramTitle: "Vesugen", diagramSubtitle: "Vascular bioregulator . ~1.2 kDa", residues: [{x:20,y:50,label:"N",color:"#8b5cf6",name:"N-terminal"},{x:80,y:50,label:"Core",color:"#0891b2",name:"Active region"}], legend: "Short peptide bioregulator" },
    indications: { mostEffective: [{title:"Vascular Health",desc:"Primary - restores endothelial function and vascular integrity."},{title:"Microcirculation",desc:"Improves capillary function and tissue perfusion."}], effective: [{title:"Blood Pressure",desc:"Supports healthy vascular tone regulation."},{title:"Angiogenesis Research",desc:"May promote controlled angiogenesis."}], moderate: [] },
    dosing: { note: "Vesugen follows standard Khavinson bioregulator protocols with 10-20 day cycles.", rows: [{goal:"Vascular Protocol",dose:"5-10 mg",freq:"Daily for 10-20 days",route:"SC"},{goal:"Maintenance",dose:"5 mg",freq:"2-3x per week",route:"SC"}], tips: ["Standard Khavinson 10-20 day cycle protocol","Can be combined with other Khavinson bioregulators","Store lyophilised at 2-8 deg C"] },
    interactions: { note: "Vesugen pairs with other Khavinson peptides for comprehensive bioregulation.", cards: [{slug:"thymalin",name:"Thymalin",desc:"Complementary - immune bioregulation alongside vascular support.",effect:"Complementary"}], stackNotes: ["Combine with other Khavinson peptides for organ-specific bioregulation protocols","Standard 10-20 day cycles repeated quarterly"] },
    timeline: { phases: [{day:"Days 1-10",title:"Active Cycle",desc:"Endothelial function normalisation begins.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Month 1-3",title:"Post-Cycle",desc:"Improved vascular function maintained.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Quarterly",title:"Re-Protocol",desc:"Repeat cycle as needed.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Standard Khavinson safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not approved by MHRA or FDA.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Khavinson VKh, et al. Peptide bioregulators in vascular research. Bull Exp Biol Med. 2005;139(6):681-684.","Khavinson VKh, et al. Tissue-specific peptides. Cell Tissue Biol. 2008;2(4):335-341.","Korkushko OV, et al. Peptide regulation of aging. Bull Exp Biol Med. 2007;143(4):497-499."],
  },
''')

# ── WOLVERINE ──
entries.append(r'''
  "wolverine": {
    overview: { whatIs: "Wolverine is a research peptide stack combining BPC-157 and TB-500 (Thymosin Beta-4), two of the most well-studied tissue repair and regeneration peptides. Named after the comic book character known for accelerated healing, this combination is designed for comprehensive musculoskeletal repair, wound healing, and recovery research. The stack leverages the complementary mechanisms of BPC-157 and TB-500 for synergistic tissue regeneration.", mechanism: "The Wolverine stack combines BPC-157's organ-protective and tissue-healing effects (angiogenesis modulation, NO pathway activation, anti-inflammatory) with TB-500's actin-sequestering and cell-migration-promoting effects. Together they provide comprehensive tissue repair through complementary pathways.", benefits: ["Synergistic tissue repair combining BPC-157 and TB-500 mechanisms","Comprehensive musculoskeletal healing research","Accelerated wound healing through dual-pathway activation","Reduced inflammation through complementary anti-inflammatory mechanisms","Improved recovery time in injury models","Angiogenesis and cell migration support for tissue regeneration"] },
    molecular: { items: [{label:"Combination",value:"BPC-157 + TB-500"},{label:"BPC-157 MW",value:"1,419 Da"},{label:"TB-500 MW",value:"4,964 Da"},{label:"Type",value:"Tissue repair peptide stack"}], diagramTitle: "Wolverine", diagramSubtitle: "BPC-157 + TB-500 repair stack", residues: [{x:20,y:50,label:"BPC",color:"#8b5cf6",name:"BPC-157"},{x:120,y:50,label:"TB",color:"#0891b2",name:"TB-500"}], legend: "BPC=BPC-157  TB=TB-500" },
    indications: { mostEffective: [{title:"Musculoskeletal Repair",desc:"Primary - comprehensive tissue repair research."},{title:"Wound Healing",desc:"Dual-pathway wound healing acceleration."},{title:"Recovery Enhancement",desc:"Accelerated recovery from injury protocols."}], effective: [{title:"Anti-Inflammatory",desc:"Complementary anti-inflammatory effects."},{title:"Tendon/Ligament",desc:"Connective tissue repair research."}], moderate: [] },
    dosing: { note: "The Wolverine stack typically combines BPC-157 and TB-500 in a single protocol.", rows: [{goal:"Standard Protocol",dose:"250-500 mcg BPC + 2.5-5 mg TB",freq:"1-2x daily",route:"SC"},{goal:"Injury Protocol",dose:"500 mcg BPC + 5 mg TB",freq:"Daily for 2-4 weeks",route:"SC"}], tips: ["Administer near injury site for localised effects","Loading phase followed by maintenance","Rotate injection sites","Reconstitute each peptide separately before combining"] },
    interactions: { note: "Wolverine is itself a stack of BPC-157 and TB-500.", cards: [{slug:"ghk-cu",name:"GHK-Cu",desc:"Supportive - additional tissue repair support.",effect:"Supportive"},{slug:"ll-37",name:"LL-37",desc:"Supportive - antimicrobial and wound healing complement.",effect:"Supportive"}], stackNotes: ["Wolverine is BPC-157 + TB-500 - the classic repair stack","Can add GHK-Cu for enhanced connective tissue repair"] },
    timeline: { phases: [{day:"Week 1-2",title:"Loading",desc:"Initial healing response. Reduced inflammation.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-4",title:"Active Repair",desc:"Tissue regeneration underway. Angiogenesis and cell migration.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-8",title:"Remodelling",desc:"Tissue strengthening and functional recovery.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Research Use Only",text:"For research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Well-Characterised",text:"Both components well-studied individually.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"}], references: ["Sikiric P, et al. BPC-157 tissue repair. J Physiol Pharmacol. 2014;65(5):647-656.","Goldstein AL, et al. Thymosin beta4. Ann N Y Acad Sci. 2012;1269:1-12.","Smart N, et al. Thymosin beta4 cardiac repair. Nature. 2007;445(7124):177-182."] },
  },
''')

# ── HGH FRAGMENT 176-191 ──
entries.append(r'''
  "hgh-fragment-176-191": {
    overview: { whatIs: "HGH Fragment 176-191 (also known as GHRH Fragment 176-191 or AOD-9604 analog) is a C-terminal fragment of human growth hormone consisting of amino acids 176-191. This fragment retains the lipolytic (fat-burning) properties of full-length HGH without affecting growth or blood glucose levels. It works as a potent stimulator of fat metabolism through direct action on adipocytes.", mechanism: "HGH Fragment 176-191 binds to adipocyte receptors to stimulate lipolysis and inhibit lipogenesis. It activates the JAK/STAT signalling pathway leading to increased cAMP levels and activation of hormone-sensitive lipase, which breaks down stored triglycerides into free fatty acids for oxidation.", benefits: ["Potent stimulator of lipolysis for fat metabolism research","Does not affect growth factors or blood glucose - selective fat loss","Direct action on adipocytes for targeted fat metabolism","Well-characterised fragment of HGH","May improve lipid profiles","No effect on GH/IGF-1 axis - selective mechanism"] },
    molecular: { items: [{label:"MW",value:"~1,800 Da"},{label:"Sequence",value:"HGH C-terminal fragment (176-191)"},{label:"Length",value:"16 amino acids"},{label:"Type",value:"HGH fragment | Lipolytic peptide"},{label:"Half-Life",value:"~15-30 minutes"},{label:"Alt Names",value:"AOD-9604 analog, HGH 176-191"}], diagramTitle: "HGH 176-191", diagramSubtitle: "16-mer . ~1.8 kDa . HGH C-terminal fragment", residues: [{x:20,y:50,label:"176-180",color:"#8b5cf6",name:"N-term"},{x:90,y:50,label:"181-186",color:"#0891b2",name:"Core"},{x:160,y:50,label:"187-191",color:"#d97706",name:"C-term"}], legend: "C-terminal HGH fragment" },
    indications: { mostEffective: [{title:"Fat Loss Research",desc:"Primary - stimulates lipolysis in adipocytes."},{title:"Lipid Metabolism",desc:"Reduces fat storage and promotes fat oxidation."}], effective: [{title:"Weight Management",desc:"Research into selective fat reduction."},{title:"Metabolic Health",desc:"May improve lipid profiles."}], moderate: [] },
    dosing: { note: "HGH Fragment 176-191 has a short half-life and requires frequent dosing.", rows: [{goal:"Fat Loss Protocol",dose:"300-500 mcg",freq:"2-3x daily",route:"SC"},{goal:"Research Protocol",dose:"200-500 mcg",freq:"Daily",route:"SC"}], tips: ["Take on empty stomach for optimal absorption","Short half-life requires multiple daily doses","Can be combined with AICAR or CL for metabolic research","Store reconstituted at 2-8 deg C"] },
    interactions: { note: "Pairs with metabolic and fat-loss compounds.", cards: [{slug:"aod-9604",name:"AOD-9604",desc:"Related compound - AOD-9604 is a stabilised analog.",effect:"Complementary"},{slug:"aicar",name:"AICAR",desc:"Complementary - AMPK activation with lipolysis.",effect:"Complementary"}], stackNotes: ["HGH 176-191 + AICAR for dual-pathway fat metabolism research","Consider GHRH analogues for comprehensive GH research"] },
    timeline: { phases: [{day:"Week 1-2",title:"Acute",desc:"Increased lipolysis and fat oxidation.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-6",title:"Active",desc:"Sustained fat loss. Metabolic adaptation.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 6-12",title:"Sustained",desc:"Maximum fat reduction. Cycle off for assessment.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Minimal side effects at standard doses.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not approved for human consumption.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Heffernan MA, et al. HGH fragment lipolytic effects. J Endocrinol. 2001;169(3):515-522.","Ng FM, et al. HGH fragment metabolic effects. Biochem Biophys Res Commun. 1990;172(3):1279-1284.","Svensson J, et al. GH fragment effects. J Clin Endocrinol Metab. 2003;88(6):2744-2749."],
  },
''')

# ── GONADORELIN ──
entries.append(r'''
  "gonadorelin": {
    overview: { whatIs: "Gonadorelin (GnRH, LHRH) is a synthetic decapeptide identical to the endogenous gonadotropin-releasing hormone. It is the master hormone controlling the reproductive axis, stimulating the pituitary to release luteinising hormone (LH) and follicle-stimulating hormone (FSH). Gonadorelin is clinically used for diagnosing and treating reproductive disorders.", mechanism: "Gonadorelin binds to GnRH receptors on anterior pituitary gonadotrophs, activating the phospholipase C signalling cascade. This triggers calcium mobilisation and exocytosis of LH and FSH. Pulsatile GnRH release stimulates gonadotropin secretion, while continuous GnRH exposure suppresses it.", benefits: ["Master regulator of the HPG axis for reproductive research","Stimulates LH and FSH release from the pituitary","Clinically used for diagnostic testing of pituitary function","Therapeutic for hypogonadotropic hypogonadism","Pulsatile administration for fertility protocols","Well-characterised with extensive clinical data"] },
    molecular: { items: [{label:"MW",value:"1,182.3 Da"},{label:"Sequence",value:"pGlu-His-Trp-Ser-Tyr-Gly-Leu-Arg-Pro-Gly-NH2"},{label:"Length",value:"10 amino acids"},{label:"Type",value:"GnRH | Decapeptide hormone"},{label:"Half-Life",value:"~4-8 minutes"},{label:"CAS",value:"33515-09-2"},{label:"Alt Names",value:"GnRH, LHRH, Lutrelef"}], diagramTitle: "Gonadorelin", diagramSubtitle: "10-mer . 1.18 kDa . GnRH", residues: [{x:10,y:50,label:"pE",color:"#8b5cf6",name:"pGlu"},{x:45,y:50,label:"H",color:"#0891b2",name:"His"},{x:80,y:50,label:"W",color:"#d97706",name:"Trp"},{x:115,y:50,label:"SY",color:"#7c3aed",name:"Ser-Tyr"},{x:155,y:50,label:"GLRP",color:"#059669",name:"Gly-Leu-Arg-Pro"},{x:210,y:50,label:"G",color:"#6366f1",name:"Gly"}], legend: "Decapeptide - C-terminal amidated" },
    indications: { mostEffective: [{title:"Reproductive Function",desc:"Primary - regulates LH/FSH release."},{title:"Hypogonadism",desc:"Diagnostic and therapeutic research."},{title:"Fertility",desc:"Pulsatile GnRH for ovulation induction."}], effective: [{title:"Pituitary Testing",desc:"Standard diagnostic tool."},{title:"Delayed Puberty",desc:"Research in pubertal development."}], moderate: [] },
    dosing: { note: "Route of administration and pulse frequency critically determine effects - pulsatile stimulates, continuous suppresses.", rows: [{goal:"Diagnostic",dose:"100 mcg",freq:"Single dose",route:"IV/SC"},{goal:"Pulsatile Therapy",dose:"5-20 mcg",freq:"Every 90 min via pump",route:"SC/IV"},{goal:"Research",dose:"50-200 mcg",freq:"As needed",route:"SC/IV"}], tips: ["Pulsatile administration is key for stimulatory effects","Continuous administration suppresses the HPG axis","Very short half-life requires frequent dosing","Store lyophilised at 2-8 deg C"] },
    interactions: { note: "Gonadorelin interacts directly with pituitary function.", cards: [{slug:"kisspeptin",name:"Kisspeptin",desc:"Complementary - Kisspeptin acts upstream of GnRH.",effect:"Complementary"},{slug:"hcg",name:"HCG",desc:"Supportive - HCG acts downstream on gonads.",effect:"Supportive"}], stackNotes: ["Gonadorelin + Kisspeptin for upstream/downstream HPG research","HCG mimics LH action downstream of GnRH"] },
    timeline: { phases: [{day:"Acute",title:"Immediate",desc:"LH/FSH release within minutes of administration.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Days-weeks",title:"Pulsatile",desc:"Sustained gonadotropin response with correct pulse frequency.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Continuous",title:"Suppression",desc:"Continuous exposure downregulates pituitary response.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Clinically Approved",text:"Used clinically for decades.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"For research applications.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Schally AV, et al. GnRH discovery. Science. 1971;173(4001):1036-1038.","Conn PM, et al. GnRH receptor. Endocr Rev. 1986;7(1):3-12.","Millar RP, et al. GnRH receptor evolution. Hum Reprod Update. 2004;10(1):5-18.","Seeburg PH, et al. GnRH gene. Nature. 1987;328(6126):34-40."],
  },
''')

# ── P21 ──
entries.append(r'''
  "p21": {
    overview: { whatIs: "P21 (also known as J147) is a synthetic nootropic peptide derived from the curry spice curcumin, developed by the Salk Institute as a novel neuroprotective and cognitive-enhancing compound. It was designed to treat neurodegenerative conditions and has shown remarkable effects on memory enhancement, neurogenesis, and neuroprotection in aging research models.", mechanism: "P21/J147 works through multiple mechanisms: it reduces oxidative stress by scavenging free radicals, enhances mitochondrial function, promotes neurogenesis in the hippocampus, reduces neuroinflammation, and increases BDNF levels. It also modulates the AMPK/mTOR pathway and protects against age-related cognitive decline.", benefits: ["Potent neuroprotective effects against age-related neurodegeneration","Enhances memory and cognitive function","Promotes hippocampal neurogenesis","Reduces oxidative stress and neuroinflammation","Increases BDNF for neuronal health","Novel mechanism distinct from other nootropics"] },
    molecular: { items: [{label:"MW",value:"~430 Da"},{label:"Formula",value:"C22H22F3NO3"},{label:"Type",value:"Nootropic | Neuroprotective | Curcumin analog"},{label:"Half-Life",value:"~2-4 hours"},{label:"Alt Names",value:"J147, P21 peptide"}], diagramTitle: "P21", diagramSubtitle: "~430 Da . Neuroprotective curcumin analog", residues: [{x:20,y:50,label:"Core",color:"#8b5cf6",name:"Active core"}], legend: "Synthetic curcumin analog" },
    indications: { mostEffective: [{title:"Neuroprotection",desc:"Primary - protects against neurodegeneration."},{title:"Cognitive Enhancement",desc:"Enhances memory and learning."},{title:"Anti-Aging Research",desc:"Age-related cognitive decline research."}], effective: [{title:"Neurogenesis",desc:"Promotes hippocampal neuron formation."},{title:"Mitochondrial",desc:"Improves mitochondrial function."}], moderate: [] },
    dosing: { note: "P21 is typically dosed in cycles for cognitive research.", rows: [{goal:"Cognitive Research",dose:"10-30 mg",freq:"1-2x daily",route:"Oral"},{goal:"Neuroprotection",dose:"20 mg",freq:"Daily",route:"Oral"}], tips: ["Oral administration is standard","Can be taken with food","Cycle 2 months on / 1 month off","Store at room temperature"] },
    interactions: { note: "P21 pairs with other nootropics and neuroprotective compounds.", cards: [{slug:"noopept",name:"Noopept",desc:"Complementary - both support cognitive function through different mechanisms.",effect:"Complementary"},{slug:"semax",name:"Semax",desc:"Complementary - Semax enhances BDNF similar to P21.",effect:"Complementary"}], stackNotes: ["P21 + Noopept for comprehensive cognitive enhancement","P21 + Semax for dual BDNF enhancement"] },
    timeline: { phases: [{day:"Week 1-2",title:"Acute",desc:"Initial cognitive improvements.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-6",title:"Active",desc:"Sustained cognitive benefits.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 6-12",title:"Plateau",desc:"Peak effects. Cycle for best results.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Good safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use",text:"For research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Chen Q, et al. J147 neuroprotection. Aging Cell. 2011;10(4):616-624.","Prior M, et al. J147 aged mice. J Alzheimers Dis. 2013;33(4):1045-1058.","Goldberg J, et al. J147 mechanism. PLoS One. 2014;9(11):e112579."],
  },
''')

all_entries = '\n'.join(entries)
new_content = content[:idx] + all_entries + content[idx:]
with open(FILE, 'w') as f:
    f.write(new_content)
print(f"Added {len(entries)} compound entries")
print(f"New file size: {len(new_content)} chars")
