#!/usr/bin/env python3
"""Add final batch of remaining compounds."""
FILE = "src/data/compound-tabs.tsx"
with open(FILE, 'r') as f:
    content = f.read()
idx = content.rfind('};')
assert idx > 0

all_entries = r'''

  "matrixyl-3000": {
    overview: { whatIs: "Matrixyl 3000 is a cosmetic peptide complex that combines two synergistic matrikines: Matrixyl (Palmitoyl-GHK) and Matrixyl Synthe'6 (Palmitoyl-GQPR). It is designed to boost collagen synthesis, reduce wrinkle depth, and improve skin firmness and elasticity. Matrixyl 3000 is one of the most researched and popular anti-aging cosmetic peptides.", mechanism: "Matrixyl 3000 delivers two complementary matrikines: Pal-GHK stimulates collagen types I and IV production, while Pal-GQPR stimulates collagen types I, II, III, and IV as well as fibronectin and hyaluronic acid. Together they activate the TGF-beta signalling pathway for comprehensive ECM remodelling.", benefits: ["Dual matrikine complex for enhanced collagen stimulation","Reduces wrinkle depth and skin roughness","Improves skin firmness, elasticity, and hydration","Stimulates multiple collagen types and ECM components","Well-researched with published clinical studies","Comprehensive anti-aging skin research"] },
    molecular: { items: [{label:"Type",value:"Cosmetic peptide complex"},{label:"Components",value:"Pal-GHK + Pal-GQPR"},{label:"Alt Names",value:"Matrixyl 3000, Matrikine complex"}], diagramTitle: "Matrixyl 3000", diagramSubtitle: "Dual matrikine complex", residues: [{x:20,y:50,label:"GHK",color:"#8b5cf6",name:"Pal-GHK"},{x:100,y:50,label:"GQPR",color:"#0891b2",name:"Pal-GQPR"}], legend: "GHK=Pal-GHK  GQPR=Pal-GQPR" },
    indications: { mostEffective: [{title:"Anti-Aging",desc:"Primary - reduces wrinkles and improves skin quality."},{title:"Collagen Stimulation",desc:"Multi-type collagen synthesis."}], effective: [{title:"Skin Firmness",desc:"Improves elasticity and hydration."},{title:"Wrinkle Reduction",desc:"Reduces deep and fine wrinkles."}], moderate: [] },
    dosing: { note: "Used in topical cosmetic formulations at recommended concentrations.", rows: [{goal:"Cosmetic",dose:"2-5% concentration",freq:"2x daily",route:"Topical"}], tips: ["Apply consistently twice daily","Combine with other cosmetic peptides","Visible results within 4-8 weeks"] },
    interactions: { note: "Pairs with other cosmetic peptides for comprehensive anti-aging.", cards: [{slug:"snap-8",name:"SNAP-8",desc:"Synergistic - Matrixyl builds collagen, SNAP-8 reduces wrinkles.",effect:"Synergistic"},{slug:"ghk-cu",name:"GHK-Cu",desc:"Complementary - both support collagen synthesis.",effect:"Complementary"}], stackNotes: ["Matrixyl 3000 + SNAP-8 + GHK-Cu = comprehensive cosmetic peptide research stack"] },
    timeline: { phases: [{day:"Week 1-4",title:"Initiation",desc:"Collagen synthesis begins.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-8",title:"Visible",desc:"Visible skin improvement.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 8-16",title:"Peak",desc:"Maximum anti-aging effects.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Excellent topical safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"}] },
    references: ["Lintner K, et al. Matrixyl. J Cosmet Sci. 2002;53(5):277-290.","Farwick M, et al. Matrixyl 3000. Int J Cosmet Sci. 2011;33(2):152-160."],
  },

  "melatonin": {
    overview: { whatIs: "Melatonin (N-acetyl-5-methoxytryptamine) is a natural hormone produced by the pineal gland that regulates the sleep-wake cycle. It is one of the most important molecules for circadian rhythm research, sleep science, and as a potent antioxidant. Melatonin levels decline with age, making it relevant for anti-aging research.", mechanism: "Melatonin binds to MT1 and MT2 receptors in the suprachiasmatic nucleus to regulate circadian timing and sleep initiation. It acts as a potent direct free radical scavenger and indirect antioxidant by stimulating antioxidant enzymes. Melatonin also modulates immune function and mitochondrial metabolism.", benefits: ["Master circadian rhythm regulator for sleep research","Potent antioxidant with direct free radical scavenging","Mitochondrial protective effects","Immune system modulation","Neuroprotective properties","Well-characterised hormone with extensive research"] },
    molecular: { items: [{label:"MW",value:"232.28 Da"},{label:"Formula",value:"C13H16N2O2"},{label:"Type",value:"Hormone | Indoleamine"},{label:"Half-Life",value:"~30-60 minutes"},{label:"CAS",value:"73-31-4"},{label:"Receptors",value:"MT1, MT2"}], diagramTitle: "Melatonin", diagramSubtitle: "232.28 Da . C13H16N2O2 . Sleep hormone", residues: [{x:20,y:50,label:"Ind",color:"#8b5cf6",name:"Indole ring"},{x:100,y:50,label:"NH",color:"#0891b2",name:"N-acetyl"}], legend: "Ind=Indole  NH=N-acetyl" },
    indications: { mostEffective: [{title:"Sleep Research",desc:"Primary - circadian rhythm regulation."},{title:"Antioxidant",desc:"Potent free radical scavenging."},{title:"Circadian Rhythm",desc:"Clock gene regulation."}], effective: [{title:"Neuroprotection",desc:"Brain antioxidant protection."},{title:"Immune Modulation",desc:"Cytokine regulation."}], moderate: [{title:"Anti-Aging",desc:"Age-related pineal decline."}] },
    dosing: { note: "Melatonin dosing varies significantly - lower doses are often more effective for sleep timing.", rows: [{goal:"Sleep Research",dose:"0.3-5 mg",freq:"30 min before bedtime",route:"Oral"},{goal:"Antioxidant",dose:"2-10 mg",freq:"15 min before bedtime",route:"Oral"}], tips: ["Lower doses (0.3-1 mg) may be more effective for sleep timing","Take 30-60 min before desired bedtime","Extended-release formulations for sleep maintenance","Protect from light - melatonin is light-sensitive"] },
    interactions: { note: "Melatonin interacts with circadian and antioxidant pathways.", cards: [{slug:"nad",name:"NAD+",desc:"Complementary - both regulate circadian rhythm through SIRT1/clock gene interactions.",effect:"Complementary"},{slug:"epithalon",name:"Epithalon",desc:"Synergistic - both support pineal function and circadian regulation.",effect:"Synergistic"}], stackNotes: ["Melatonin + Epithalon for comprehensive pineal and circadian research","Melatonin + NAD+ for clock gene and sirtuin pathway investigation"] },
    timeline: { phases: [{day:"Day 1",title:"Acute",desc:"Immediate sleep timing effects.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Adaptation",desc:"Circadian entrainment.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Ongoing",title:"Sustained",desc:"Maintained circadian rhythm.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Endogenous Hormone",text:"Natural hormone - good safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Daytime Use",text:"May cause drowsiness if taken during the day.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Reiter RJ. Melatonin. Endocr Rev. 1991;12(2):151-180.","Hardeland R, et al. Melatonin antioxidant. J Pineal Res. 2005;39(4):321-337.","Brzezinski A. Melatonin in humans. N Engl J Med. 1997;336(3):186-195."],
  },

  "cagrilintide": {
    overview: { whatIs: "Cagrilintide is a long-acting amylin analogue developed for metabolic research, representing a next-generation approach to weight management and metabolic health. As an amylin receptor agonist, it complements GLP-1-based therapies by targeting a different satiety pathway for enhanced metabolic outcomes.", mechanism: "Cagrilintide activates amylin receptors in the area postrema of the brainstem, reducing food intake by promoting satiety and slowing gastric emptying. Unlike GLP-1 agonists, amylin acts through a separate, complementary pathway for appetite regulation.", benefits: ["Long-acting amylin receptor agonist","Promotes satiety and reduces food intake","Complementary mechanism to GLP-1 agonists","Slows gastric emptying for prolonged fullness","Novel metabolic research application","Weekly dosing due to extended half-life"] },
    molecular: { items: [{label:"Type",value:"Amylin analogue | Long-acting"},{label:"Target",value:"Amylin receptors"},{label:"Half-Life",value:"~7-10 days"}], diagramTitle: "Cagrilintide", diagramSubtitle: "Long-acting amylin analogue", residues: [{x:20,y:50,label:"Amylin",color:"#8b5cf6",name:"Amylin analog"}], legend: "Amylin receptor agonist" },
    indications: { mostEffective: [{title:"Weight Management",desc:"Primary - reduces food intake through amylin receptor activation."},{title:"Metabolic Health",desc:"Complementary GLP-1 research pathway."}], effective: [], moderate: [] },
    dosing: { note: "Weekly dosing due to extended half-life.", rows: [{goal:"Metabolic",dose:"0.3-4.5 mg",freq:"Once weekly",route:"SC"}], tips: ["Titrate dose gradually","Weekly administration only","Use alongside GLP-1 agonists for dual pathway research"] },
    interactions: { note: "Primarily studied with GLP-1 agonists.", cards: [{slug:"semaglutide",name:"Semaglutide",desc:"Synergistic - dual GLP-1/amylin agonism for enhanced metabolic research.",effect:"Synergistic"},{slug:"tirzepatide",name:"Tirzepatide",desc:"Complementary - dual GIP/GLP-1 + amylin pathway research.",effect:"Complementary"}], stackNotes: ["Cagrilintide + Semaglutide for GLP-1 + amylin dual pathway research","Triple pathways: GLP-1 + GIP + amylin for comprehensive metabolic research"] },
    timeline: { phases: [{day:"Week 1",title:"Initiation",desc:"Amylin receptor activation.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-8",title:"Active",desc:"Progressive appetite reduction.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 8-24",title:"Assessment",desc:"Maximum metabolic effects.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Novel Research",text:"Emerging research compound.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Research Use Only",text:"Not approved for human consumption.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Krueger T, et al. Cagrilintide. Lancet. 2021;397(10288):1918-1928.","Larsen PJ, et al. Amylin receptor agonist. Br J Pharmacol. 2020;177(10):2325-2338."],
  },

  "survodutide": {
    overview: { whatIs: "Survodutide is a novel dual GLP-1/glucagon receptor agonist being researched for metabolic disease. It represents an emerging incretin-based therapeutic approach combining the appetite-suppressing effects of GLP-1 agonism with the energy-expending effects of glucagon receptor activation.", mechanism: "Survodutide simultaneously activates GLP-1 receptors (appetite suppression, improved insulin secretion, slowed gastric emptying) and glucagon receptors (increased energy expenditure, hepatic lipolysis) for comprehensive metabolic modulation.", benefits: ["Dual GLP-1/glucagon receptor agonist","Enhanced weight loss through combined mechanisms","Improved metabolic parameters","Novel incretin research tool","Extended half-life for weekly dosing"] },
    molecular: { items: [{label:"Type",value:"Dual GLP-1/Glucagon agonist"},{label:"Targets",value:"GLP-1R + GCGR"},{label:"Half-Life",value:"~5-7 days"}], diagramTitle: "Survodutide", diagramSubtitle: "Dual GLP-1/glucagon agonist" },
    indications: { mostEffective: [{title:"Weight Loss",desc:"Primary - dual mechanism metabolic research."},{title:"Metabolic Health",desc:"Comprehensive metabolic effects."}], effective: [], moderate: [] },
    dosing: { note: "Weekly dosing due to extended half-life.", rows: [{goal:"Metabolic",dose:"0.5-4 mg",freq:"Once weekly",route:"SC"}], tips: ["Weekly dosing schedule","Titrate gradually"] },
    interactions: { note: "Compare with other incretin compounds.", cards: [{slug:"mazdutide",name:"Mazdutide",desc:"Alternative - similar GLP-1/glucagon dual agonist.",effect:"Complementary"},{slug:"retatrutide",name:"Retatrutide",desc:"Alternative - triple agonist (GIP/GLP-1/glucagon).",effect:"Complementary"}], stackNotes: ["Survodutide joins the class of dual GLP-1/glucagon agonists alongside Mazdutide"] },
    timeline: { phases: [{day:"Week 1",title:"Initiation",desc:"Receptor activation.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-8",title:"Active",desc:"Metabolic effects.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 8-24",title:"Assessment",desc:"Maximum effects.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Novel Research",text:"Emerging compound.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Research Only",text:"Not for human consumption.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Day JW, et al. Dual GLP-1/glucagon agonists. Nat Chem Biol. 2009;5(10):749-757."],
  },

  "hmg": {
    overview: { whatIs: "HMG (Human Menopausal Gonadotropin) is a hormone preparation containing equal amounts of follicle-stimulating hormone (FSH) and luteinising hormone (LH) activity, extracted from the urine of postmenopausal women. It is used in fertility research and for studying gonadotropin function in the hypothalamic-pituitary-gonadal axis.", mechanism: "HMG provides exogenous FSH and LH to stimulate gonadal function. FSH stimulates follicle development in females and spermatogenesis in males. LH stimulates testosterone production in males and ovulation in females.", benefits: ["Dual FSH and LH activity for reproductive research","Clinically used in fertility treatment","Supports gonadal function studies","Well-characterised hormone preparation"] },
    molecular: { items: [{label:"Type",value:"Gonadotropin preparation"},{label:"Components",value:"FSH + LH (equal activity)"}], diagramTitle: "HMG", diagramSubtitle: "FSH + LH preparation" },
    indications: { mostEffective: [{title:"Fertility Research",desc:"Primary - ovulation induction and spermatogenesis."},{title:"Gonadal Function",desc:"HPT axis research."}], effective: [], moderate: [] },
    dosing: { note: "Dosing varies by research protocol.", rows: [{goal:"Fertility",dose:"75-225 IU",freq:"Daily",route:"SC/IM"}], tips: ["Reconstitute carefully with sterile water","Use immediately after reconstitution"] },
    interactions: { note: "Part of gonadotropin research pathway.", cards: [{slug:"hcg",name:"HCG",desc:"Complementary - HCG provides LH-like activity.",effect:"Complementary"},{slug:"gonadorelin",name:"Gonadorelin",desc:"Upstream - GnRH stimulates endogenous FSH/LH.",effect:"Supportive"}], stackNotes: ["HMG + HCG for comprehensive gonadotropin research"] },
    timeline: { phases: [{day:"Days 1-10",title:"Stimulation",desc:"Gonadal stimulation begins.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Clinically Used",text:"Approved for fertility treatment.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Hormonal",text:"Affects natural hormone production.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Lunenfeld B, et al. HMG development. Gynecol Endocrinol. 2004;19(3):115-121.","Practice Committee of ASRM. HMG use. Fertil Steril. 2008;90(5 Suppl):S168-S174."],
  },

  "tesofensine": {
    overview: { whatIs: "Tesofensine is a triple monoamine reuptake inhibitor that acts on serotonin, norepinephrine, and dopamine transporters. Originally developed for Alzheimer's and Parkinson's disease, it was found to produce significant weight loss through appetite suppression and increased energy expenditure.", mechanism: "Tesofensine inhibits the reuptake of serotonin, norepinephrine, and dopamine by blocking their respective transporters (SERT, NET, DAT). This increases synaptic concentrations of these neurotransmitters, reducing appetite through enhanced satiety signalling and increasing metabolic rate.", benefits: ["Triple monoamine reuptake inhibitor (SERT/NET/DAT)","Significant appetite suppression for weight loss research","Increases energy expenditure and metabolic rate","Well-characterised clinical pharmacology","Distinct mechanism from GLP-1 based approaches"] },
    molecular: { items: [{label:"MW",value:"~338 Da"},{label:"Formula",value:"C17H23Cl2NO"},{label:"Type",value:"Triple reuptake inhibitor"},{label:"Half-Life",value:"~9 days"},{label:"Targets",value:"SERT, NET, DAT"}], diagramTitle: "Tesofensine", diagramSubtitle: "~338 Da . Triple reuptake inhibitor", residues: [{x:20,y:50,label:"Core",color:"#8b5cf6",name:"Active core"}], legend: "SERT/NET/DAT inhibitor" },
    indications: { mostEffective: [{title:"Weight Loss",desc:"Primary - significant appetite suppression."},{title:"Metabolic Research",desc:"Energy expenditure increase."}], effective: [{title:"Cognitive",desc:"Originally studied for cognition."}], moderate: [] },
    dosing: { note: "Tesofensine has a very long half-life (~9 days) requiring once-daily or less frequent dosing.", rows: [{goal:"Weight Loss",dose:"0.25-0.5 mg",freq:"Once daily",route:"Oral"}], tips: ["Very long half-life - steady state takes ~4 weeks","Start at lowest dose (0.25 mg)","Morning dosing recommended"] },
    interactions: { note: "Interacts with monoamine systems.", cards: [{slug:"semaglutide",name:"Semaglutide",desc:"Complementary - different mechanism for weight loss research.",effect:"Complementary"}], stackNotes: ["Tesofensine + GLP-1 agonist for dual pathway weight loss research","Avoid other serotonergic compounds"] },
    timeline: { phases: [{day:"Week 1-4",title:"Titration",desc:"Steady state achieved.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-12",title:"Active",desc:"Maximum appetite suppression.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 12-24",title:"Sustained",desc:"Sustained weight loss effects.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Characterised",text:"Clinical safety data available.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Side Effects",text:"Insomnia, dry mouth, nausea possible at higher doses.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Research Use Only",text:"Not approved by MHRA/FDA.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Astrup A, et al. Tesofensine weight loss. Lancet. 2008;372(9652):1906-1913.","Hansen HH, et al. Tesofensine pharmacology. J Pharmacol Exp Ther. 2010;332(2):421-430."],
  },

  "gnrh-triptorelin": {
    overview: { whatIs: "Triptorelin is a synthetic decapeptide analogue of gonadotropin-releasing hormone (GnRH) with enhanced potency and duration of action. Unlike pulsatile GnRH which stimulates the HPG axis, triptorelin is a GnRH agonist that, when administered continuously, suppresses gonadotropin release through receptor downregulation.", mechanism: "Triptorelin binds to GnRH receptors with higher affinity than native GnRH. After an initial stimulatory phase (flare), continuous administration downregulates pituitary GnRH receptors, suppressing LH and FSH secretion and reducing sex steroid production.", benefits: ["Potent GnRH receptor agonist with extended duration","Biphasic effect - initial flare then suppression","Continuous administration for HPG axis suppression","Clinically used for hormone-sensitive conditions","Well-characterised peptide pharmacology"] },
    molecular: { items: [{label:"MW",value:"~1,312 Da"},{label:"Sequence",value:"Modified GnRH decapeptide"},{label:"Type",value:"GnRH agonist"},{label:"Half-Life",value:"~3-4 hours"},{label:"Alt Names",value:"Triptorelin, GnRH agonist"}], diagramTitle: "Triptorelin", diagramSubtitle: "GnRH agonist . ~1.3 kDa" },
    indications: { mostEffective: [{title:"HPG Axis Suppression",desc:"Primary - continuous administration suppresses gonadotropins."},{title:"Hormone Research",desc:"Sex steroid modulation studies."}], effective: [], moderate: [] },
    dosing: { note: "Continuous administration is key for suppressive effects.", rows: [{goal:"Suppression",dose:"100-500 mcg",freq:"Daily",route:"SC"},{goal:"Depot",dose:"3.75 mg",freq:"Monthly",route:"SC/IM"}], tips: ["Continuous daily dosing needed for suppression","Depot formulations available for monthly dosing"] },
    interactions: { note: "Interacts with HPG axis compounds.", cards: [{slug:"gonadorelin",name:"Gonadorelin",desc:"Alternative - pulsatile GnRH stimulates, continuous triptorelin suppresses.",effect:"Complementary"}], stackNotes: ["Contrasts with pulsatile GnRH (stimulatory) vs continuous triptorelin (suppressive)"] },
    timeline: { phases: [{day:"Day 1-3",title:"Flare",desc:"Initial stimulation of LH/FSH.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Suppression",desc:"GnRH receptor downregulation.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Month 1-6",title:"Sustained",desc:"Maintained HPG suppression.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Clinically Used",text:"Approved for hormone therapy.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Hormonal Effects",text:"Sex steroid suppression effects.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Schally AV, et al. GnRH analogues. Hum Reprod. 2000;15(Suppl 2):17-35.","Conn PM, et al. GnRH receptor. N Engl J Med. 1991;324(2):93-103."],
  },

  "myostatin": {
    overview: { whatIs: "Myostatin (GDF-8) is a growth differentiation factor that acts as a negative regulator of muscle growth. It is a member of the TGF-beta superfamily and is expressed primarily in skeletal muscle. Myostatin inhibition has been a major focus of muscle growth research, as blocking myostatin leads to significant muscle mass increases.", mechanism: "Myostatin binds to activin type II receptors (ActRIIB), activating SMAD2/3 signalling which suppresses myoblast proliferation and differentiation. It negatively regulates muscle growth by inhibiting Akt/mTOR signalling and promoting protein degradation.", benefits: ["Negative regulator of muscle growth - central to muscle research","Target for muscle wasting and sarcopenia research","Inhibition leads to significant muscle mass increase","Well-characterised TGF-beta family member","Key target for muscle growth pathway research"] },
    molecular: { items: [{label:"MW",value:"~25 kDa (dimer)"},{label:"Type",value:"TGF-beta superfamily | Growth factor"},{label:"Receptor",value:"ActRIIB"}], diagramTitle: "Myostatin", diagramSubtitle: "~25 kDa . GDF-8 . Negative muscle regulator" },
    indications: { mostEffective: [{title:"Muscle Wasting Research",desc:"Primary - negative regulator of muscle growth."},{title:"Sarcopenia",desc:"Age-related muscle loss research."},{title:"Muscle Growth",desc:"Inhibition studies for anabolic research."}], effective: [], moderate: [] },
    dosing: { note: "Myostatin inhibition requires specific research protocols.", rows: [{goal:"Inhibition Research",dose:"Varies by approach",freq:"Varies",route:"SC/IV"}], tips: ["Myostatin inhibitors include Follistatin, ActRIIB-Fc, and myostatin antibodies"] },
    interactions: { note: "Myostatin interacts with muscle growth pathways.", cards: [{slug:"follistatin",name:"Follistatin",desc:"Complementary - Follistatin is a natural myostatin inhibitor.",effect:"Synergistic"},{slug:"igf-1-lr3",name:"IGF-1 LR3",desc:"Complementary - IGF-1 activates muscle growth while myostatin suppresses it - dual pathway research.",effect:"Complementary"}], stackNotes: ["Follistatin + Myostatin research for negative regulation pathway investigation"] },
    timeline: { phases: [{day:"Week 1-4",title:"Initiation",desc:"Myostatin pathway manipulation.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-12",title:"Active",desc:"Muscle growth assessment.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Research Use Only",text:"For research purposes.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["McPherron AC, et al. Myostatin. Nature. 1997;387(6628):83-90.","Lee SJ, et al. Myostatin regulation. J Biol Chem. 2001;276(8):5953-5959.","Whittemore LA, et al. Myostatin inhibition. Biochem Biophys Res Commun. 2003;300(4):965-971."],
  },

  "n-acetyl-semax-amidate": {
    overview: { whatIs: "N-Acetyl-Semax Amidate is a stabilised synthetic analogue of Semax (a heptapeptide derived from ACTH), with modifications that enhance its stability and CNS penetration. It is a nootropic peptide studied for cognitive enhancement, neuroprotection, and anxiolytic effects.", mechanism: "N-Acetyl-Semax Amidate modulates BDNF and NGF expression in the brain, enhances dopamine and serotonin neurotransmission, and protects neurons from oxidative stress. The acetylation and C-terminal amidation protect against enzymatic degradation.", benefits: ["Enhanced stability and CNS penetration vs Semax","Increases BDNF and NGF for neuroplasticity","Cognitive enhancement and memory improvement","Neuroprotective effects","Anxiolytic properties"] },
    molecular: { items: [{label:"Type",value:"Nootropic peptide | Semax analog"},{label:"Modifications",value:"N-acetylated + C-terminal amidated"}], diagramTitle: "NA-Semax-Amidate", diagramSubtitle: "Stabilised Semax analogue" },
    indications: { mostEffective: [{title:"Cognitive Enhancement",desc:"Primary - memory and learning improvement."},{title:"Neuroprotection",desc:"Neural protection and recovery."}], effective: [{title:"Anxiety",desc:"Anxiolytic effects."},{title:"Neuroplasticity",desc:"BDNF/NGF upregulation."}], moderate: [] },
    dosing: { note: "Follow Semax-based protocols with the amidate form.", rows: [{goal:"Cognitive",dose:"400-800 mcg",freq:"1-2x daily",route:"Intranasal"},{goal:"Neuroprotection",dose:"400-800 mcg",freq:"1-2x daily",route:"Intranasal"}], tips: ["Intranasal administration preferred for CNS delivery","Can be stacked with other nootropics"] },
    interactions: { note: "Pairs with other nootropics.", cards: [{slug:"noopept",name:"Noopept",desc:"Complementary - dual nootropic pathway.",effect:"Complementary"},{slug:"selank",name:"Selank",desc:"Synergistic - both ACTH-derived peptides.",effect:"Synergistic"}], stackNotes: ["NA-Semax-Amidate + Selank for dual ACTH-derived peptide research"] },
    timeline: { phases: [{day:"Day 1-7",title:"Acute",desc:"Initial cognitive improvement.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-6",title:"Sustained",desc:"BDNF upregulation.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Good safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Only",text:"Not MHRA/FDA approved.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Levitskaya NG, et al. Semax analogues. Eksp Klin Farmakol. 2002;65(3):3-7.","Dmitrieva VG, et al. Semax BDNF. Mol Biol. 2010;44(5):793-800."],
  },

  "n-acetyl-selank-amidate": {
    overview: { whatIs: "N-Acetyl-Selank Amidate is a stabilised synthetic analogue of Selank, a heptapeptide derived from the immune system protein tuftsin. It is studied for its anxiolytic, neuroprotective, and cognitive effects. The modifications enhance its stability and CNS penetration.", mechanism: "N-Acetyl-Selank Amidate modulates enkephalin metabolism and cytokine balance, enhancing GABAergic and serotonergic neurotransmission. It reduces anxiety through modulation of the IL-6 and TNF-alpha cytokine pathways.", benefits: ["Enhanced stability vs Selank through modifications","Potent anxiolytic effects","Neuroprotective properties","Cognitive modulation","Immunomodulatory effects"] },
    molecular: { items: [{label:"Type",value:"Anxiolytic peptide | Selank analog"},{label:"Modifications",value:"N-acetylated + C-terminal amidated"}], diagramTitle: "NA-Selank-Amidate", diagramSubtitle: "Stabilised Selank analogue" },
    indications: { mostEffective: [{title:"Anxiolytic",desc:"Primary - anxiety research."},{title:"Neuroprotection",desc:"Neural protection."}], effective: [{title:"Cognitive",desc:"Memory and learning modulation."}], moderate: [] },
    dosing: { note: "Follow Selank-based protocols.", rows: [{goal:"Anxiolytic",dose:"400-900 mcg",freq:"1-2x daily",route:"Intranasal"}], tips: ["Intranasal for CNS delivery","Can be cycled with other nootropics"] },
    interactions: { note: "Pairs with other ACTH-derived peptides.", cards: [{slug:"n-acetyl-semax-amidate",name:"NA-Semax-Amidate",desc:"Synergistic - both stabilised ACTH-derived peptides.",effect:"Synergistic"}], stackNotes: ["NA-Selank-Amidate + NA-Semax-Amidate for comprehensive ACTH peptide research"] },
    timeline: { phases: [{day:"Day 1-3",title:"Acute",desc:"Anxiolytic effects.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Sustained",desc:"Neuroprotective benefits.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Good safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Only",text:"Not approved for human use.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Kozlovskii IL, et al. Selank pharmacology. Eksp Klin Farmakol. 2002;65(3):8-12.","Sollertinskaya TN, et al. Selank effects. Zh Vyssh Nerv Deiat. 2003;53(4):473-478."],
  },
'''

new_content = content[:idx] + all_entries + content[idx:]
with open(FILE, 'w') as f:
    f.write(new_content)
print(f"Added batch with 10 compounds")
print(f"New file size: {len(new_content)} chars")
