#!/usr/bin/env python3
"""Add next batch of compounds."""
FILE = "src/data/compound-tabs.tsx"
with open(FILE, 'r') as f:
    content = f.read()
idx = content.rfind('};')
assert idx > 0, "Could not find closing };"

all_entries = r'''

  "l-carnitine": {
    overview: { whatIs: "L-Carnitine is a quaternary ammonium compound synthesised from lysine and methionine that plays an essential role in energy metabolism by transporting long-chain fatty acids into the mitochondrial matrix for beta-oxidation. It is found in nearly all cells and is particularly concentrated in skeletal and cardiac muscle where fatty acid oxidation is the primary energy source. L-Carnitine exists in two forms: L-carnitine (biologically active) and acetyl-L-carnitine (ALCAR), which has enhanced brain penetration for neurological research.", mechanism: "L-Carnitine acts as a shuttle for long-chain fatty acids across the inner mitochondrial membrane via the carnitine palmitoyltransferase (CPT) system. CPT1 converts fatty acyl-CoA to acyl-carnitine on the outer membrane, which is then transported across by carnitine-acylcarnitine translocase (CACT) and converted back to acyl-CoA by CPT2 inside the mitochondrial matrix for beta-oxidation. It also buffers excess acyl-CoA groups and modulates the mitochondrial acetyl-CoA/CoA ratio.", benefits: ["Essential for mitochondrial fatty acid transport and beta-oxidation energy production","Improves exercise performance and recovery through enhanced fat metabolism","Supports cardiovascular health through improved cardiac energy metabolism","Neuroprotective effects particularly with acetyl-L-carnitine form","Insulin-sensitising effects through improved mitochondrial function","Reduces oxidative stress and supports mitochondrial health"] },
    molecular: { items: [{label:"MW",value:"161.20 Da"},{label:"Formula",value:"C7H15NO3"},{label:"Type",value:"Amino acid derivative | Mitochondrial shuttle"},{label:"Half-Life",value:"~8-12 hours"},{label:"CAS",value:"541-15-1"},{label:"Alt Names",value:"L-Carnitine, Levocarnitine, Vitamin BT"}], diagramTitle: "L-Carnitine", diagramSubtitle: "161.20 Da . C7H15NO3 . Fatty acid shuttle", residues: [{x:20,y:50,label:"N+",color:"#8b5cf6",name:"Trimethylamine"},{x:80,y:50,label:"OH",color:"#0891b2",name:"Hydroxyl"},{x:140,y:50,label:"COO",color:"#d97706",name:"Carboxylate"}], legend: "N+=Trimethylammonium  OH=Hydroxyl  COO=Carboxylate" },
    indications: { mostEffective: [{title:"Fatty Acid Oxidation",desc:"Primary - shuttles long-chain fatty acids into mitochondria for energy production."},{title:"Exercise Performance",desc:"Improves exercise capacity and reduces muscle damage markers."},{title:"Mitochondrial Support",desc:"Essential for mitochondrial energy metabolism and function."}], effective: [{title:"Cardiovascular",desc:"Supports cardiac energy metabolism and function."},{title:"Neuroprotection",desc:"ALCAR form supports brain energy metabolism."},{title:"Insulin Sensitivity",desc:"Improves metabolic flexibility and insulin signalling."}], moderate: [{title:"Anti-Aging",desc:"Mitochondrial support for healthy aging research."},{title:"Male Fertility",desc:"Supports sperm motility and quality."}] },
    dosing: { note: "L-Carnitine is water-soluble with moderate oral bioavailability. Acetyl-L-carnitine has better CNS penetration.", rows: [{goal:"General Health",dose:"500-2000 mg",freq:"1-2x daily",route:"Oral"},{goal:"Exercise Performance",dose:"1000-2000 mg",freq:"1x pre-workout",route:"Oral"},{goal:"Therapeutic",dose:"200-400 mg",freq:"1-2x daily",route:"SC/IM"}], tips: ["Oral bioavailability is 5-15% - higher doses compensate","ALCAR (acetyl-L-carnitine) preferred for neurological research","Best taken with carbohydrates for enhanced muscle uptake","Vitamin C and B6 support endogenous carnitine synthesis"] },
    interactions: { note: "L-Carnitine pairs with mitochondrial and metabolic support compounds.", cards: [{slug:"nad",name:"NAD+",desc:"Synergistic - both support mitochondrial energy metabolism through complementary pathways.",effect:"Synergistic"},{slug:"glutathione",name:"Glutathione",desc:"Complementary - carnitine supports energy while glutathione provides antioxidant protection.",effect:"Complementary"},{slug:"ss-31",name:"SS-31",desc:"Synergistic - both target mitochondrial function through different mechanisms.",effect:"Synergistic"}], stackNotes: ["L-Carnitine + NAD+ for comprehensive mitochondrial energy support","ALCAR + Glutathione for combined neurological and antioxidant support","Consider coenzyme Q10 for complete mitochondrial electron transport chain support"] },
    timeline: { phases: [{day:"Day 1-7",title:"Acute",desc:"Immediate improvement in fatty acid oxidation. Increased energy availability.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-4",title:"Adaptation",desc:"Tissue carnitine levels increase. Improved exercise performance and recovery.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-12",title:"Sustained",desc:"Metabolic improvements established. Consistent benefits maintained.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Generally Safe",text:"Endogenous compound with excellent safety profile at standard doses.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"GI Effects",text:"High oral doses may cause mild digestive discomfort.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"TMAO",text:"Very high doses may increase TMAO production - relevant in cardiovascular research.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}], references: ["Rebouche CJ. Carnitine function and metabolism. FASEB J. 1992;6(15):3379-3386.","Stephens FB, et al. Carnitine fat metabolism. J Lipid Res. 2007;48(12):2600-2608.","Fielding R, et al. L-Carnitine exercise performance. Nutr Metab. 2018;15:33.","Foster DW. Carnitine system. Annu Rev Nutr. 2004;24:301-322."] },
  },

  "snap-8": {
    overview: { whatIs: "SNAP-8 (Acetyl Octapeptide-3) is a synthetic peptide engineered as an improved version of Argireline for reducing expression wrinkles. It consists of eight amino acids that inhibit neurotransmitter release at the neuromuscular junction, reducing muscle contraction intensity. SNAP-8 is approximately 10 times more potent than Argireline and is one of the most popular cosmetic peptides for reducing the appearance of expression wrinkles, particularly on the forehead and around the eyes.", mechanism: "SNAP-8 mimics the N-terminal end of SNAP-25, a key component of the SNARE complex required for neurotransmitter vesicle fusion with the presynaptic membrane. By competing with SNAP-25 for binding sites, SNAP-8 partially inhibits acetylcholine release, reducing muscle contraction intensity responsible for dynamic wrinkle formation without the complete paralysis seen with neurotoxins.", benefits: ["Approximately 10x more potent than Argireline for reducing expression lines","Reduces forehead wrinkles, crow's feet, and frown lines","Non-invasive alternative to neuromodulators","Reversible mechanism - function returns upon discontinuation","Targets SNARE complex for neurotransmitter release modulation","Well-tolerated topical peptide with extensive cosmetic safety data"] },
    molecular: { items: [{label:"MW",value:"~1,016 Da"},{label:"Sequence",value:"Modified octapeptide"},{label:"Length",value:"8 amino acids"},{label:"Type",value:"Cosmetic peptide | SNARE inhibitor"},{label:"Alt Names",value:"Acetyl Octapeptide-3, SNAP-8"}], diagramTitle: "SNAP-8", diagramSubtitle: "~1.0 kDa . SNARE complex inhibitor", residues: [{x:10,y:50,label:"Ac",color:"#8b5cf6",name:"Acetyl"},{x:60,y:50,label:"EE",color:"#0891b2",name:"Glu-Glu"},{x:110,y:50,label:"MQR",color:"#d97706",name:"Core"},{x:170,y:50,label:"RAD",color:"#059669",name:"C-term"}], legend: "Ac=Acetyl group  Mimics SNAP-25 N-terminus" },
    indications: { mostEffective: [{title:"Expression Wrinkles",desc:"Primary - reduces forehead lines and crow's feet through SNARE complex inhibition."},{title:"Cosmetic Anti-Aging",desc:"Non-invasive alternative to neuromodulators for wrinkle prevention."}], effective: [{title:"Periocular Wrinkles",desc:"Reduces crow's feet and periorbital fine lines."},{title:"Perioral Wrinkles",desc:"May reduce lip lines."}], moderate: [{title:"Research",desc:"Tool for studying SNARE complex function."}] },
    dosing: { note: "SNAP-8 is primarily used in topical cosmetic formulations at 5-20% concentrations.", rows: [{goal:"Topical Cosmetic",dose:"5-20%",freq:"2x daily",route:"Topical"},{goal:"Research",dose:"10-50 mcg per site",freq:"2-3x per week",route:"SC"}], tips: ["Topical is the standard route for cosmetic use","Consistent daily use required for visible results over 4-8 weeks","Apply to clean dry skin","Combine with GHK-Cu and Matrixyl for comprehensive anti-aging"] },
    interactions: { note: "SNAP-8 pairs with other cosmetic peptides.", cards: [{slug:"ghk-cu",name:"GHK-Cu",desc:"Complementary - GHK-Cu for collagen while SNAP-8 prevents wrinkles.",effect:"Complementary"},{slug:"matrixyl-3000",name:"Matrixyl 3000 (to add)",desc:"Synergistic - Matrixyl boosts collagen while SNAP-8 prevents wrinkle formation.",effect:"Synergistic"}], stackNotes: ["SNAP-8 + GHK-Cu + Matrixyl 3000 = cosmetic peptide triad","SNAP-8 is 10x more potent than Argireline"] },
    timeline: { phases: [{day:"Week 1-2",title:"Initiation",desc:"SNARE complex inhibition begins.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 3-6",title:"Visible",desc:"Reduction in dynamic wrinkle formation.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 6-12",title:"Peak",desc:"Maximum wrinkle reduction. Reversible upon discontinuation.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Excellent cosmetic safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not approved for human injection.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Reversible",text:"Full reversibility upon discontinuation.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}], references: ["Blanes-Mira C, et al. Synthetic antiwrinkle peptide. Int J Cosmet Sci. 2002;24(5):303-310.","Lupo MP, et al. Cosmetic peptides. Dermatol Surg. 2005;31(7 Pt 2):832-836.","Gorouhi F, et al. Peptides in cosmeceuticals. Dermatol Ther. 2014;27(2):97-104."] },
  },

  "melanotan-ii": {
    overview: { whatIs: "Melanotan II (MT-II) is a synthetic cyclic heptapeptide analogue of the naturally occurring melanocyte-stimulating hormone (alpha-MSH). It was originally developed as a sunless tanning agent at the University of Arizona but gained significant research interest for its effects on melanogenesis and sexual function. MT-II is a non-selective melanocortin receptor agonist, binding to MC1R (melanogenesis), MC3R/MC4R (appetite/energy), and MC5R (sebaceous gland) receptors.", mechanism: "Melanotan II binds to melanocortin receptors (MC1R-MC5R) with highest affinity for MC1R and MC4R. MC1R activation in melanocytes stimulates tyrosinase activity, increasing eumelanin (brown-black pigment) production independent of UV exposure. MC4R activation in the hypothalamus modulates appetite, energy expenditure, and sexual arousal. The dual action on pigmentation and sexual function distinguishes MT-II from selective melanocortin agonists.", benefits: ["Stimulates melanogenesis for UV-independent tanning through MC1R activation","Enhances sexual arousal and function through MC3R/MC4R hypothalamic activation","Reduces appetite through central melanocortin signalling","May protect against UV-induced DNA damage through increased eumelanin","Long-lasting effects - single dose can maintain tan for weeks","Well-characterised peptide with extensive clinical research"] },
    molecular: { items: [{label:"MW",value:"~1,024 Da"},{label:"Sequence",value:"Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-NH2"},{label:"Length",value:"7 amino acids (cyclic heptapeptide)"},{label:"Type",value:"Melanocortin agonist | Tanning peptide"},{label:"Half-Life",value:"~30-60 minutes"},{label:"CAS",value:"121062-08-6"},{label:"Alt Names",value:"MT-II, Melanotan 2, Melanotan II"}], diagramTitle: "MT-II", diagramSubtitle: "7-mer cyclic . ~1.0 kDa . Melanocortin agonist", residues: [{x:10,y:50,label:"Ac",color:"#8b5cf6",name:"Acetyl"},{x:50,y:50,label:"Nle",color:"#0891b2",name:"Nle"},{x:90,y:50,label:"D",color:"#d97706",name:"Asp"},{x:130,y:50,label:"H",color:"#7c3aed",name:"His"},{x:170,y:50,label:"f",color:"#059669",name:"D-Phe"},{x:210,y:50,label:"R",color:"#6366f1",name:"Arg"},{x:250,y:50,label:"W",color:"#db2777",name:"Trp"},{x:290,y:50,label:"K",color:"#06b6d4",name:"Lys"}], legend: "Ac=Acetyl  Nle=Norleucine  f=D-Phe  Cyclic peptide" },
    indications: { mostEffective: [{title:"UV-Independent Tanning",desc:"Primary - stimulates eumelanin production through MC1R activation without UV exposure."},{title:"Sexual Dysfunction",desc:"Enhances sexual arousal through MC3R/MC4R hypothalamic activation."},{title:"Erythropoietic Protoporphyria",desc:"Increases skin pigmentation to protect against light sensitivity in EPP patients."}], effective: [{title:"Appetite Suppression",desc:"Reduces food intake through central MC4R signalling."},{title:"Erectile Dysfunction",desc:"Promotes spontaneous erections through melanocortin pathway activation."}], moderate: [{title:"Sun Protection",desc:"Increased eumelanin provides natural SPF protection."}] },
    dosing: { note: "MT-II is typically dosed as a short course to achieve desired pigmentation, then maintained at lower frequency.", rows: [{goal:"Tanning Protocol",dose:"0.5-1 mg",freq:"Every other day for 10 doses",route:"SC"},{goal:"Maintenance",dose:"0.5-1 mg",freq:"1-2x per week",route:"SC"},{goal:"Sexual Function",dose:"0.25-0.5 mg",freq:"As needed 30 min before",route:"SC"}], tips: ["Start with low dose (0.25 mg) to assess response and minimise nausea","Titrate up gradually over first week","Dose in evening to reduce nausea side effects","Sun exposure still requires SPF protection","Reconstitute with bacteriostatic water; swirl gently","Store reconstituted at 2-8 deg C; use within 28 days"] },
    interactions: { note: "MT-II interacts with melanocortin and sexual function pathways.", cards: [{slug:"pt-141",name:"PT-141",desc:"Alternative - PT-141 (Bremelanotide) is a selective MC3R/MC4R agonist without tanning effects, derived from MT-II.",effect:"Complementary"},{slug:"oxytocin",name:"Oxytocin",desc:"Complementary - both modulate sexual function through different neuropeptide pathways.",effect:"Complementary"}], stackNotes: ["MT-II for combined tanning and sexual function research","PT-141 for sexual function research without pigmentation effects","Avoid concurrent MAOIs due to potential interactions"] },
    timeline: { phases: [{day:"Day 1-3",title:"Loading",desc:"Initial melanogenesis stimulation. Possible nausea at higher doses.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Day 3-10",title:"Pigmentation",desc:"Visible skin darkening begins. Progressively deepening tan over 10 doses.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-12",title:"Maintenance",desc:"Tan maintained with 1-2x weekly dosing. Fades gradually after discontinuation.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Research Use Only",text:"Not approved by MHRA or FDA for cosmetic use. Research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Nausea",text:"Nausea is the most common side effect, especially at higher doses. Starting low and titrating helps.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Mole Darkening",text:"Existing moles and freckles may darken disproportionately - monitor in research.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Libido Effects",text:"Spontaneous erections and increased libido may occur through MC4R activation.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Hadley ME, et al. Melanocortin peptides for sunless tanning. Pigment Cell Res. 2006;19(4):346-353.","Dorr RT, et al. Melanotan II safety. Life Sci. 1996;58(20):1777-1784.","Wessells H, et al. Melanotan II sexual function. J Urol. 1998;160(2):389-393.","King SH, et al. Melanocortin receptors. Peptides. 2006;27(2):383-392.","Ugwu SO, et al. Melanotan II pharmacokinetics. J Pharm Sci. 1994;83(12):1741-1744."],
  },

  "noopept": {
    overview: { whatIs: "Noopept (N-phenylacetyl-L-prolylglycine ethyl ester) is a synthetic nootropic peptide developed in Russia that belongs to the racetam family structurally but acts through different mechanisms. It is one of the most popular nootropic compounds, known for its cognitive-enhancing, neuroprotective, and anxiolytic effects at very low doses. Noopept is approximately 1000 times more potent than piracetam and produces rapid-onset cognitive benefits.", mechanism: "Noopept is a prodrug that is metabolised to cycloprolylglycine, which acts as a nootropic agent, and phenylacetic acid. It modulates AMPA and NMDA glutamate receptors, enhances cholinergic transmission, increases NGF and BDNF expression, and acts as a calcium channel modulator. Noopept also has antioxidant properties and protects mitochondria from oxidative damage.", benefits: ["Approximately 1000x more potent than piracetam for cognitive enhancement","Rapid onset of action within 15-30 minutes of administration","Neuroprotective effects through antioxidant and anti-excitotoxic mechanisms","Enhances memory formation and recall through glutamate receptor modulation","Increases BDNF and NGF expression for neuronal health","Anxiolytic effects through GABAergic modulation"] },
    molecular: { items: [{label:"MW",value:"334.37 Da"},{label:"Formula",value:"C17H22N2O5"},{label:"Type",value:"Nootropic peptide | Prodrug"},{label:"Half-Life",value:"~2-3 hours"},{label:"CAS",value:"157115-85-0"},{label:"Alt Names",value:"N-phenylacetyl-L-prolylglycine ethyl ester"}], diagramTitle: "Noopept", diagramSubtitle: "334.37 Da . C17H22N2O5 . Nootropic peptide", residues: [{x:15,y:50,label:"Phenyl",color:"#8b5cf6",name:"Phenylacetyl"},{x:80,y:50,label:"Pro",color:"#0891b2",name:"Prolyl"},{x:145,y:50,label:"Gly",color:"#d97706",name:"Glycine"},{x:210,y:50,label:"OEt",color:"#059669",name:"Ethyl ester"}], legend: "Phenyl=Phenylacetyl  Pro=Prolyl  Gly=Glycine  OEt=Ethyl ester" },
    indications: { mostEffective: [{title:"Cognitive Enhancement",desc:"Primary - enhances memory, learning, and cognitive processing."},{title:"Neuroprotection",desc:"Protects neurons from oxidative stress and excitotoxicity."},{title:"Anxiety Reduction",desc:"Anxiolytic effects through GABAergic modulation."}], effective: [{title:"Memory Consolidation",desc:"Enhances memory formation and recall."},{title:"Mental Clarity",desc:"Improves focus and mental processing speed."}], moderate: [{title:"Mood Enhancement",desc:"Mild mood-elevating effects reported."}] },
    dosing: { note: "Noopept is active at very low doses (10-30 mg) and should be cycled to maintain efficacy.", rows: [{goal:"Cognitive Enhancement",dose:"10-20 mg",freq:"1-2x daily",route:"Sublingual/Oral"},{goal:"Neuroprotection",dose:"10 mg",freq:"1-2x daily",route:"Sublingual"},{goal:"Stacking Protocol",dose:"10-20 mg",freq:"1-2x daily",route:"Sublingual"}], tips: ["Sublingual administration provides faster onset and better bioavailability","Do not exceed 30 mg per dose","Cycle 2 months on / 1 month off to prevent tolerance","Best taken in the morning to avoid sleep disruption","Avoid with stimulants for first use to assess individual response"] },
    interactions: { note: "Noopept stacks well with other nootropics and cognitive enhancers.", cards: [{slug:"selank",name:"Selank",desc:"Synergistic - Selank provides additional anxiolytic effects while Noopept enhances cognition.",effect:"Synergistic"},{slug:"semax",name:"Semax",desc:"Synergistic - both enhance BDNF and cognitive function through complementary pathways.",effect:"Synergistic"},{slug:"oxytocin",name:"Oxytocin",desc:"Complementary - Noopept for cognition, oxytocin for social cognition.",effect:"Complementary"}], stackNotes: ["Noopept + Semax = the classic Russian nootropic stack","Noopept + Selank for cognition with anxiety reduction","Cycle nootropics to maintain sensitivity"] },
    timeline: { phases: [{day:"Day 1-3",title:"Acute",desc:"Immediate cognitive enhancement within 15-30 min. Improved focus and clarity.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Adaptation",desc:"Sustained cognitive benefits. Memory consolidation improvements.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-8",title:"Plateau",desc:"Peak effects achieved. Consider cycling to prevent tolerance.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Good safety profile at recommended low doses.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not approved by MHRA or FDA. For research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Tolerance",text:"May develop tolerance with continuous use - cycling recommended.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Irritability",text:"Some users report mild irritability at higher doses.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}], references: ["Gudasheva TA, et al. Noopept pharmacology. Pharm Chem J. 1996;30(2):73-78.","Ostrovskaya RU, et al. Noopept neuroprotection. Bull Exp Biol Med. 2002;134(5):458-462.","Seredenin SB, et al. Noopept clinical study. Eksp Klin Farmakol. 2003;66(1):13-16.","Gudasheva TA, et al. Noopept mechanism. Eksp Klin Farmakol. 2007;70(1):7-11."] },
  },
'''

new_content = content[:idx] + all_entries + content[idx:]

with open(FILE, 'w') as f:
    f.write(new_content)

print(f"Added batch with {all_entries.count(chr(34)+': {')} compounds")
print(f"New file size: {len(new_content)} chars")
