#!/usr/bin/env python3
"""Add remaining single-variant compounds in one batch."""
FILE = "src/data/compound-tabs.tsx"
with open(FILE, 'r') as f:
    content = f.read()
idx = content.rfind('};')
assert idx > 0

all_entries = r'''

  "phenylpiracetam": {
    overview: { whatIs: "Phenylpiracetam (Phenylpiracetam, Carphedon) is a nootropic compound from the racetam family, developed in Russia as a more potent derivative of piracetam with a phenyl group addition that enhances potency and allows it to cross the blood-brain barrier more effectively. It is known for its stimulant-nootropic effects, improving cognitive function, physical endurance, and stress resistance.", mechanism: "Phenylpiracetam modulates AMPA and NMDA glutamate receptors, enhances cholinergic neurotransmission, and increases dopamine D2 receptor density. It also improves mitochondrial function and energy metabolism in neurons, increases oxygen utilisation, and enhances physical endurance through effects on the CNS rather than peripheral mechanisms.", benefits: ["More potent than Piracetam with improved BBB penetration","Enhances cognitive function, memory, and learning","Improves physical endurance and stress resistance","Modulates dopamine and glutamate receptor systems","Increases oxygen utilisation in the brain","Well-characterised Russian nootropic"] },
    molecular: { items: [{label:"MW",value:"~272 Da"},{label:"Formula",value:"C12H14N2O2"},{label:"Type",value:"Nootropic | Racetam"},{label:"Half-Life",value:"~3-5 hours"},{label:"Alt Names",value:"Carphedon, Phenotropil"}], diagramTitle: "Phenylpiracetam", diagramSubtitle: "272 Da . C12H14N2O2 . Racetam nootropic", residues: [{x:20,y:50,label:"Phe",color:"#8b5cf6",name:"Phenyl"},{x:90,y:50,label:"Pyrr",color:"#0891b2",name:"Pyrrolidone"}], legend: "Phe=Phenyl group  Pyrr=Pyrrolidone ring" },
    indications: { mostEffective: [{title:"Cognitive Enhancement",desc:"Primary - improves memory and learning."},{title:"Physical Endurance",desc:"Unique - enhances physical performance."}], effective: [{title:"Stress Resistance",desc:"Improves adaptation to stress."},{title:"Fatigue Reduction",desc:"Reduces mental and physical fatigue."}], moderate: [{title:"Neuroprotection",desc:"May protect against cognitive decline."}] },
    dosing: { note: "Phenylpiracetam is typically taken 1-2x daily with cycling to maintain efficacy.", rows: [{goal:"Cognitive",dose:"100-200 mg",freq:"1-2x daily",route:"Oral"},{goal:"Physical",dose:"200 mg",freq:"1x pre-activity",route:"Oral"}], tips: ["Start with lower dose to assess tolerance","Cycle 2 months on / 1 month off","Take in the morning to avoid sleep disruption","Can be stacked with other nootropics"] },
    interactions: { note: "Pairs well with other racetams and nootropics.", cards: [{slug:"noopept",name:"Noopept",desc:"Complementary - both racetam-family nootropics.",effect:"Complementary"},{slug:"p21",name:"P21 (to add)",desc:"Complementary - different mechanism cognitive support.",effect:"Complementary"}], stackNotes: ["Phenylpiracetam + Noopept for dual racetam cognitive enhancement","Consider choline source to prevent headaches"] },
    timeline: { phases: [{day:"Day 1",title:"Acute",desc:"Immediate cognitive and stimulant effects.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Sustained",desc:"Cognitive improvements maintained.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-8",title:"Plateau",desc:"Consider cycling for best results.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Good safety profile at recommended doses.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use",text:"For research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Bobkova NV, et al. Phenylpiracetam effects. Eksp Klin Farmakol. 2004;67(4):3-6.","Zvejniece L, et al. Phenylpiracetam pharmacology. Basic Clin Pharmacol Toxicol. 2011;109(1):32-38."],
  },

  "pramipexole": {
    overview: { whatIs: "Pramipexole is a dopamine D2/D3 receptor agonist used primarily in the treatment of Parkinson's disease and restless legs syndrome. As a research compound, it is studied for its effects on dopamine signalling, neuroprotection, cognitive function, and potential applications in depression and bipolar disorder research.", mechanism: "Pramipexole selectively binds to D2 and D3 dopamine receptors with highest affinity for D3 receptors. It activates the postsynaptic dopamine signalling cascade, compensating for dopamine deficiency. It also has antioxidant properties, protects mitochondrial function, and upregulates neurotrophic factors.", benefits: ["Selective D2/D3 dopamine receptor agonist","Neuroprotective effects in dopamine neuron models","Antioxidant and mitochondrial protection","Potential cognitive and mood modulation","Well-characterised clinical pharmacology"] },
    molecular: { items: [{label:"MW",value:"~211 Da"},{label:"Formula",value:"C10H17N3S"},{label:"Type",value:"Dopamine agonist | Aminobenzothiazole"},{label:"Half-Life",value:"~8-12 hours"},{label:"Receptors",value:"D2 > D3 dopamine"}], diagramTitle: "Pramipexole", diagramSubtitle: "211 Da . D2/D3 agonist", residues: [{x:20,y:50,label:"BTZ",color:"#8b5cf6",name:"Benzothiazole"}], legend: "Dopamine D2/D3 agonist" },
    indications: { mostEffective: [{title:"Dopamine Research",desc:"Primary - D2/D3 receptor agonist studies."},{title:"Neuroprotection",desc:"Protects dopamine neurons."}], effective: [{title:"Cognitive Research",desc:"Dopamine-mediated cognitive effects."},{title:"Mood Research",desc:"Potential antidepressant applications."}], moderate: [] },
    dosing: { note: "Doses vary significantly by research protocol. Start low and titrate.", rows: [{goal:"Dopamine Research",dose:"0.125-0.5 mg",freq:"1-3x daily",route:"Oral"}], tips: ["Start at lowest dose and titrate slowly","Take with food to reduce nausea"] },
    interactions: { note: "Pramipexole interacts with the dopamine system.", cards: [], stackNotes: ["Avoid concurrent high-dose antipsychotics which block dopamine receptors"] },
    timeline: { phases: [{day:"Week 1-2",title:"Initiation",desc:"Dopamine receptor activation.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-6",title:"Active",desc:"Sustained dopamine modulation.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 6-12",title:"Assessment",desc:"Evaluate research outcomes.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Clinically Approved",text:"Approved for Parkinson's disease.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Side Effects",text:"Nausea, dizziness, impulse control effects possible.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Piercey MF, et al. Pramipexole pharmacology. J Pharmacol Exp Ther. 1996;276(3):1215-1226.","Schapira AH, et al. Pramipexole neuroprotection. Neurology. 2006;66(10 Suppl 4):S12-S18."],
  },

  "hcg": {
    overview: { whatIs: "Human Chorionic Gonadotropin (HCG) is a glycoprotein hormone produced during pregnancy that acts as a luteinising hormone (LH) analogue. It is used clinically for fertility treatment and research into reproductive function, testosterone production, and the hypothalamic-pituitary-gonadal axis. HCG stimulates Leydig cells in males to produce testosterone.", mechanism: "HCG binds to LH/HCG receptors on Leydig cells (males) and theca cells (females), activating the cAMP/PKA signalling cascade. In males, it stimulates testosterone production. In females, it triggers ovulation and supports the corpus luteum.", benefits: ["LH receptor agonist for testosterone research","Supports reproductive function studies","Clinically used for fertility treatments","Well-characterised hormone","Restores testicular function in HPT axis research"] },
    molecular: { items: [{label:"MW",value:"~25,700 Da (dimer)"},{label:"Type",value:"Glycoprotein hormone"},{label:"Half-Life",value:"~24-36 hours"},{label:"Subunits",value:"Alpha + Beta"}], diagramTitle: "HCG", diagramSubtitle: "~25.7 kDa . Glycoprotein hormone", residues: [{x:20,y:50,label:"A",color:"#8b5cf6",name:"Alpha subunit"},{x:90,y:50,label:"B",color:"#0891b2",name:"Beta subunit"}], legend: "Alpha + Beta dimer" },
    indications: { mostEffective: [{title:"Testosterone Research",desc:"Primary - stimulates Leydig cell testosterone production."},{title:"Fertility Research",desc:"Ovulation induction and gonadal function."}], effective: [{title:"HPT Axis",desc:"Hypothalamic-pituitary-gonadal research."}], moderate: [] },
    dosing: { note: "HCG is typically dosed 2-3x per week for testosterone research protocols.", rows: [{goal:"Testosterone",dose:"250-500 IU",freq:"2-3x per week",route:"SC/IM"},{goal:"Fertility",dose:"5,000-10,000 IU",freq:"Single dose",route:"IM"}], tips: ["Reconstitute carefully with bacteriostatic water","Use immediately after reconstitution","Rotate injection sites","Store lyophilised at 2-8 deg C"] },
    interactions: { note: "HCG interacts with the HPT axis.", cards: [{slug:"gonadorelin",name:"Gonadorelin",desc:"Complementary - GnRH acts upstream of HCG.",effect:"Complementary"},{slug:"kisspeptin",name:"Kisspeptin",desc:"Complementary - upstream regulator.",effect:"Complementary"}], stackNotes: ["HCG mimics LH for testosterone research","Combine with GnRH for full HPT axis investigation"] },
    timeline: { phases: [{day:"Day 1",title:"Acute",desc:"Testosterone increase within 24-48 hours.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Sustained",desc:"Elevated testosterone maintained with repeated dosing.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-12",title:"Assessment",desc:"Evaluate HPT axis response.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Clinically Approved",text:"Approved for fertility treatment.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Hormonal",text:"Affects natural hormone production - monitor levels.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Pierce JG, et al. HCG structure. J Biol Chem. 1971;246(7):2038-2047.","Choi J, et al. HCG and testosterone. J Androl. 2000;21(6):831-837."],
  },

  "klow": {
    overview: { whatIs: "K-LOW is a research peptide blend combining GHK-Cu (copper peptide), BPC-157, TB-500, and KPV - four powerful regenerative peptides for comprehensive tissue repair, anti-aging, and skin health research. The blend is designed for synergistic effects on wound healing, collagen synthesis, angiogenesis, and inflammation modulation.", mechanism: "The K-LOW blend leverages the complementary mechanisms of its components: GHK-Cu stimulates collagen synthesis and antioxidant gene expression; BPC-157 promotes tissue repair and organ protection; TB-500 enhances cell migration and angiogenesis; KPV provides anti-inflammatory and antimicrobial effects through melanocortin receptor activation.", benefits: ["Comprehensive tissue repair from four synergistic peptides","Enhanced collagen synthesis and skin health","Angiogenesis and cell migration support","Anti-inflammatory and antimicrobial protection","Multi-pathway wound healing approach","Covers multiple repair mechanisms simultaneously"] },
    molecular: { items: [{label:"Combination",value:"GHK-Cu + BPC-157 + TB-500 + KPV"},{label:"Types",value:"Copper peptide + Repair peptides + Anti-inflammatory"}], diagramTitle: "K-LOW", diagramSubtitle: "Quadruple repair peptide blend", residues: [{x:15,y:50,label:"GHK",color:"#8b5cf6",name:"GHK-Cu"},{x:70,y:50,label:"BPC",color:"#0891b2",name:"BPC-157"},{x:125,y:50,label:"TB",color:"#d97706",name:"TB-500"},{x:180,y:50,label:"KPV",color:"#059669",name:"KPV"}], legend: "GHK=GHK-Cu  BPC=BPC-157  TB=TB-500  KPV=KPV" },
    indications: { mostEffective: [{title:"Tissue Repair",desc:"Primary - multi-pathway repair research."},{title:"Skin Health",desc:"Collagen and connective tissue research."},{title:"Anti-Inflammatory",desc:"Reduced inflammation through KPV."}], effective: [{title:"Wound Healing",desc:"Accelerated tissue regeneration."},{title:"Anti-Aging",desc:"Comprehensive tissue rejuvenation."}], moderate: [] },
    dosing: { note: "K-LOW blend dosing follows individual component protocols.", rows: [{goal:"Repair Protocol",dose:"0.5-1 ml",freq:"Daily",route:"SC"}], tips: ["Follow individual component dosing guidelines","Can be injected near target tissue","Rotate injection sites"] },
    interactions: { note: "K-LOW already contains all components for comprehensive repair.", cards: [], stackNotes: ["K-LOW is a complete repair stack - contains GHK-Cu, BPC-157, TB-500, and KPV","No additional stacking usually needed"] },
    timeline: { phases: [{day:"Week 1-2",title:"Initiation",desc:"Multi-pathway repair activation.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-6",title:"Active Repair",desc:"Sustained tissue regeneration.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 6-12",title:"Remodelling",desc:"Tissue strengthening.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Research Use Only",text:"For research use only.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Multi-Component",text:"Assess each component individually.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["See individual component references for GHK-Cu, BPC-157, TB-500, KPV."],
  },

  "mazdutide": {
    overview: { whatIs: "Mazdutide is a dual GLP-1 and glucagon receptor agonist developed for metabolic research, combining the appetite-suppressing effects of GLP-1 agonism with the energy-expending effects of glucagon receptor activation. It represents a next-generation approach to metabolic disease research beyond single-receptor GLP-1 agonists.", mechanism: "Mazdutide simultaneously activates GLP-1 receptors (reducing appetite, slowing gastric emptying, improving insulin secretion) and glucagon receptors (increasing energy expenditure, hepatic glucose production, and lipolysis) for comprehensive metabolic modulation.", benefits: ["Dual GLP-1/glucagon agonist for metabolic research","Enhanced weight loss through combined appetite suppression and energy expenditure","Improved metabolic parameters","Next-generation incretin research tool","Greater efficacy potential than single-receptor agonists"] },
    molecular: { items: [{label:"Type",value:"Dual GLP-1/Glucagon receptor agonist"},{label:"Targets",value:"GLP-1R + GCGR"},{label:"Half-Life",value:"~5-7 days"}], diagramTitle: "Mazdutide", diagramSubtitle: "Dual GLP-1/glucagon agonist", residues: [{x:20,y:50,label:"GLP-1",color:"#8b5cf6",name:"GLP-1 activity"},{x:100,y:50,label:"Glu",color:"#0891b2",name:"Glucagon activity"}], legend: "Dual receptor agonist" },
    indications: { mostEffective: [{title:"Weight Loss Research",desc:"Primary - dual mechanism metabolic research."},{title:"Metabolic Health",desc:"Comprehensive metabolic parameter improvement."}], effective: [], moderate: [] },
    dosing: { note: "Mazdutide is dosed weekly due to its extended half-life.", rows: [{goal:"Metabolic Research",dose:"2-6 mg",freq:"Once weekly",route:"SC"}], tips: ["Weekly dosing schedule","Titrate dose gradually","Store at 2-8 deg C"] },
    interactions: { note: "Compare with other incretin-based compounds.", cards: [{slug:"tirzepatide",name:"Tirzepatide",desc:"Alternative - Tirzepatide is GIP/GLP-1 dual agonist; Mazdutide is GLP-1/glucagon.",effect:"Complementary"},{slug:"retatrutide",name:"Retatrutide",desc:"Alternative - Retatrutide is triple agonist (GIP/GLP-1/glucagon).",effect:"Complementary"}], stackNotes: ["Mazdutide (GLP-1/glucagon) vs Tirzepatide (GIP/GLP-1) vs Retatrutide (triple)"] },
    timeline: { phases: [{day:"Week 1",title:"Initiation",desc:"Receptor activation begins.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 2-8",title:"Active",desc:"Progressive metabolic effects.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 8-24",title:"Assessment",desc:"Maximum metabolic effects.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Novel Research",text:"Emerging compound - limited long-term data.",icon:"M12 8v4m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Research Use Only",text:"Not approved for human consumption.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Day JW, et al. GLP-1/glucagon dual agonist. Nat Chem Biol. 2009;5(10):749-757.","Pocai A, et al. Dual agonist metabolic effects. Cell Metab. 2009;10(3):207-217."],
  },

  "hgh-97": {
    overview: { whatIs: "HGH-97 is a synthetic growth hormone fragment studied for its potential effects on metabolism, body composition, and tissue repair. It represents a specific fragment of the human growth hormone molecule designed for targeted research applications.", mechanism: "HGH-97 interacts with growth hormone receptors to modulate metabolic signalling pathways, potentially influencing lipolysis, protein synthesis, and cellular growth processes through selective GH receptor activation.", benefits: ["Targeted GH fragment for metabolism research","Potential lipolytic effects","May support protein synthesis research","Alternative to full-length HGH for specific studies"] },
    molecular: { items: [{label:"Type",value:"HGH fragment peptide"},{label:"Alt Names",value:"HGH-97, growth hormone fragment"}], diagramTitle: "HGH-97", diagramSubtitle: "GH fragment peptide" },
    indications: { mostEffective: [{title:"Metabolism Research",desc:"GH fragment metabolic effects."}], effective: [], moderate: [] },
    dosing: { note: "Research compound - follow published protocols.", rows: [{goal:"Research",dose:"100-500 mcg",freq:"1-2x daily",route:"SC"}], tips: ["Follow standard peptide handling protocols"] },
    interactions: { note: "Interacts with GH pathway compounds.", cards: [], stackNotes: [] },
    timeline: { phases: [{day:"Week 1-4",title:"Research Period",desc:"Metabolic assessment.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Research Use Only",text:"Not for human consumption.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Research compound - refer to supplier documentation."],
  },

  "pal-ghk": {
    overview: { whatIs: "PAL-GHK (Palmitoyl-GHK) is a palmitoylated derivative of the copper peptide GHK-Cu, designed for enhanced topical delivery in cosmetic formulations. The palmitoyl group improves lipid solubility and skin penetration, making it ideal for cosmeceutical research into anti-aging, collagen stimulation, and skin repair.", mechanism: "PAL-GHK delivers the active GHK tripeptide to skin cells through improved membrane penetration via the palmitoyl group. Once internalised, GHK stimulates collagen and elastin synthesis, promotes angiogenesis, and modulates antioxidant gene expression for comprehensive skin repair and anti-aging effects.", benefits: ["Enhanced skin penetration through palmitoylation","Stimulates collagen and elastin synthesis","Promotes skin repair and regeneration","Antioxidant and anti-inflammatory effects","Superior topical delivery vs GHK-Cu alone"] },
    molecular: { items: [{label:"MW",value:"~588 Da"},{label:"Sequence",value:"Pal-Gly-His-Lys"},{label:"Type",value:"Palmitoylated copper peptide"},{label:"Alt Names",value:"Palmitoyl-GHK, Pal-GHK"}], diagramTitle: "PAL-GHK", diagramSubtitle: "Palmitoyl-Gly-His-Lys", residues: [{x:15,y:50,label:"Pal",color:"#8b5cf6",name:"Palmitoyl"},{x:80,y:50,label:"G",color:"#0891b2",name:"Gly"},{x:125,y:50,label:"H",color:"#d97706",name:"His"},{x:170,y:50,label:"K",color:"#059669",name:"Lys"}], legend: "Pal=Palmitoyl  G=Gly  H=His  K=Lys" },
    indications: { mostEffective: [{title:"Cosmetic Anti-Aging",desc:"Primary - collagen stimulation and skin repair."},{title:"Wrinkle Reduction",desc:"Improves skin firmness and elasticity."}], effective: [{title:"Skin Repair",desc:"Supports wound healing and tissue regeneration."}], moderate: [] },
    dosing: { note: "PAL-GHK is used in topical cosmetic formulations.", rows: [{goal:"Topical Cosmetic",dose:"2-5% concentration",freq:"2x daily",route:"Topical"}], tips: ["Apply to clean, dry skin","Combine with moisturiser","Consistent daily use for visible results"] },
    interactions: { note: "Pairs with other cosmetic peptides.", cards: [{slug:"snap-8",name:"SNAP-8",desc:"Complementary - SNAP-8 reduces wrinkles while PAL-GHK builds collagen.",effect:"Synergistic"}], stackNotes: ["PAL-GHK + SNAP-8 for comprehensive cosmetic peptide research"] },
    timeline: { phases: [{day:"Week 1-4",title:"Initiation",desc:"Collagen synthesis begins.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-12",title:"Active",desc:"Visible skin improvement.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Excellent topical safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not approved for human injection.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Pickart L, et al. GHK-Cu skin effects. J Cosmet Sci. 2008;59(6):485-494.","Gruber JV, et al. Pal-GHK skin delivery. Int J Cosmet Sci. 2010;32(5):381-389."],
  },

  "pinealon": {
    overview: { whatIs: "Pinealon is a synthetic peptide bioregulator developed by Khavinson for the pineal gland and central nervous system. It is designed to protect and restore neuronal function, regulate circadian rhythm, and provide neuroprotection in age-related cognitive decline research.", mechanism: "Pinealon acts as a tissue-specific bioregulator for neural and pineal tissues, normalising gene expression and protein synthesis. It protects neurons from oxidative stress, enhances neurotransmitter synthesis, and supports the pineal gland's role in circadian regulation.", benefits: ["Neuroprotective effects on brain tissue","Supports pineal gland function and circadian rhythm","Enhances cognitive function in aging research","Protects against oxidative stress in neurons","Khavinson peptide bioregulator for CNS"] },
    molecular: { items: [{label:"Type",value:"Peptide bioregulator | CNS"},{label:"Alt Names",value:"Pinealon peptide, Khavinson CNS peptide"}], diagramTitle: "Pinealon", diagramSubtitle: "Neural peptide bioregulator" },
    indications: { mostEffective: [{title:"Neuroprotection",desc:"Primary - protects neural tissue."},{title:"Cognitive Aging",desc:"Age-related cognitive decline research."}], effective: [{title:"Circadian Rhythm",desc:"Pineal gland support."},{title:"Antioxidant",desc:"Neural oxidative stress protection."}], moderate: [] },
    dosing: { note: "Standard Khavinson 10-20 day cycle protocol.", rows: [{goal:"Neuroprotection",dose:"5-10 mg",freq:"Daily for 10-20 days",route:"SC"}], tips: ["Use with other Khavinson bioregulators","Cycles repeated quarterly"] },
    interactions: { note: "Part of the Khavinson bioregulator system.", cards: [{slug:"epithalon",name:"Epithalon",desc:"Synergistic - both target pineal function.",effect:"Synergistic"},{slug:"thymalin",name:"Thymalin",desc:"Complementary - immune and CNS bioregulation.",effect:"Complementary"}], stackNotes: ["Pinealon + Epithalon for comprehensive pineal research"] },
    timeline: { phases: [{day:"Days 1-10",title:"Active Cycle",desc:"Neural protection initiated.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Month 1-3",title:"Post-Cycle",desc:"Sustained benefits.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Quarterly",title:"Re-Protocol",desc:"Repeat as needed.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Standard Khavinson safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not FDA/MHRA approved.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Khavinson VKh, et al. Peptide bioregulators. Bull Exp Biol Med. 2005;140(5):594-596.","Khavinson VKh, et al. Neural peptide effects. Adv Gerontol. 2007;20(4):33-38."],
  },

  "lipo-c": {
    overview: { whatIs: "Lipo-C is a specialised lipotropic compound designed for metabolic research into fat metabolism, liver health, and energy production. It typically contains a combination of lipotropic agents that support the liver's ability to process and eliminate fat.", mechanism: "Lipo-C supports hepatic lipid metabolism by enhancing fatty acid oxidation, promoting bile production, and supporting the methylation cycle for efficient fat processing and elimination.", benefits: ["Supports hepatic fat metabolism research","Enhances fatty acid oxidation","May improve lipid profiles","Energy production support","Liver function research applications"] },
    molecular: { items: [{label:"Type",value:"Lipotropic compound"}], diagramTitle: "Lipo-C", diagramSubtitle: "Fat metabolism support" },
    indications: { mostEffective: [{title:"Fat Metabolism",desc:"Primary - lipotropic fat processing research."},{title:"Liver Health",desc:"Hepatic lipid metabolism."}], effective: [{title:"Energy",desc:"Metabolic energy support."}], moderate: [] },
    dosing: { note: "Follow specific product protocol.", rows: [{goal:"Metabolic",dose:"1-2 ml",freq:"1-2x per week",route:"SC/IM"}], tips: ["Rotate injection sites","Can be combined with other metabolic compounds"] },
    interactions: { note: "Pairs with other metabolic compounds.", cards: [], stackNotes: ["Lipo-C + L-Carnitine for enhanced fat metabolism research"] },
    timeline: { phases: [{day:"Week 1-4",title:"Initiation",desc:"Metabolic support begins.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-12",title:"Active",desc:"Sustained metabolic effects.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Well-Tolerated",text:"Good safety profile.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Research Use Only",text:"Not for human consumption.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Research compound - refer to supplier documentation."],
  },

  "pnc-27": {
    overview: { whatIs: "PNC-27 is a synthetic peptide composed of a partial sequence of the tumour suppressor protein p53 conjugated to a cell-penetrating peptide (the N-terminus of p53 with an antennapedia homeodomain). It is studied for selective cancer cell cytotoxicity, as it specifically targets and kills cancer cells while sparing normal cells.", mechanism: "PNC-27 binds to the HDM-2 protein that is overexpressed in many cancer cells. The p53 peptide displaces endogenous p53 from HDM-2 binding, releasing p53 to trigger apoptosis. The cell-penetrating peptide ensures selective uptake by cancer cells, which overexpress HDM-2 on their surface.", benefits: ["Selective cancer cell cytotoxicity","Targets HDM-2 overexpressed in cancer cells","Sparing of normal, healthy cells","p53-mediated apoptosis induction","Novel targeted cancer research approach"] },
    molecular: { items: [{label:"Type",value:"p53-HDM-2 targeted peptide"},{label:"Mechanism",value:"p53 reactivation via HDM-2 binding"},{label:"Alt Names",value:"PNC-27, p53 penetrating peptide"}], diagramTitle: "PNC-27", diagramSubtitle: "p53-HDM-2 targeted peptide" },
    indications: { mostEffective: [{title:"Cancer Research",desc:"Primary - selective cancer cell apoptosis."},{title:"HDM-2 Targeting",desc:"p53 pathway reactivation."}], effective: [], moderate: [] },
    dosing: { note: "Research compound - follow published protocols.", rows: [{goal:"Cancer Research",dose:"5-50 uM",freq:"Varies",route:"In vitro/IP"}], tips: ["Handle with appropriate safety protocols","Research use only"] },
    interactions: { note: "Novel targeted cancer research compound.", cards: [], stackNotes: ["Research into p53 pathway reactivation"] },
    timeline: { phases: [{day:"Varies",title:"Research Protocol",desc:"Cell-specific study timeline.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Research Only",text:"Potent research compound.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"},{label:"Cytotoxic",text:"Selective but potent cytotoxic agent.",icon:"M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636",color:"red"}] },
    references: ["Watters JM, et al. PNC-27 cancer targeting. Mol Cancer Ther. 2004;3(8):971-980.","Do TN, et al. PNC-27 mechanism. Int J Oncol. 2011;38(6):1713-1721."],
  },

  "pe-22-28": {
    overview: { whatIs: "PE-22-28 is a peptide fragment derived from the beta-amyloid precursor protein, studied for its role in neuroprotection and cognitive function. It represents a research tool for understanding Alzheimer's disease pathology and potential neuroprotective interventions.", mechanism: "PE-22-28 modulates beta-amyloid processing and signalling pathways involved in neurodegeneration. It may interfere with amyloid aggregation and protect neurons from amyloid-induced toxicity.", benefits: ["Neuroprotection in amyloid research","Potential cognitive function support","Alzheimer's disease research tool","Anti-amyloid properties"] },
    molecular: { items: [{label:"Type",value:"Amyloid precursor peptide fragment"}], diagramTitle: "PE-22-28", diagramSubtitle: "APP fragment peptide" },
    indications: { mostEffective: [{title:"Neuroprotection",desc:"Primary - amyloid research."}], effective: [], moderate: [] },
    dosing: { note: "Research compound - follow published protocols.", rows: [{goal:"Research",dose:"10-100 uM",freq:"Varies",route:"In vitro"}], tips: ["Research use only - in vitro studies"] },
    interactions: { note: "Novel neuroprotection research compound.", cards: [], stackNotes: [] },
    timeline: { phases: [{day:"Varies",title:"Research",desc:"Study-dependent timeline.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"}] },
    safety: { cards: [{label:"Research Only",text:"For laboratory research use.",icon:"M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z",color:"amber"}] },
    references: ["Research peptide - refer to literature for specific applications."],
  },

  "vitamin-b12": {
    overview: { whatIs: "Vitamin B12 (Cobalamin) is an essential water-soluble vitamin that plays a critical role in red blood cell formation, DNA synthesis, neurological function, and energy metabolism. It is one of the most important B vitamins, and deficiency can lead to anaemia, neurological problems, and fatigue. Injectable B12 is used for research into energy, cognitive function, and methylation support.", mechanism: "Vitamin B12 acts as a cofactor for two essential enzymes: methionine synthase (methylation cycle, homocysteine metabolism) and methylmalonyl-CoA mutase (fatty acid metabolism). It supports myelin production, neurotransmitter synthesis, and red blood cell maturation.", benefits: ["Essential for red blood cell formation and DNA synthesis","Critical for neurological function and myelin production","Energy metabolism support","Methylation cycle cofactor","Homocysteine regulation","Well-characterised essential vitamin"] },
    molecular: { items: [{label:"MW",value:"~1,355 Da"},{label:"Formula",value:"C63H88CoN14O14P"},{label:"Type",value:"Vitamin | Cobalamin"},{label:"Forms",value:"Methylcobalamin, Cyanocobalamin, Adenosylcobalamin"},{label:"CAS",value:"68-19-9 (methylcobalamin)"}], diagramTitle: "B12", diagramSubtitle: "~1.36 kDa . Cobalamin", residues: [{x:20,y:50,label:"Cor",color:"#8b5cf6",name:"Corrin ring"},{x:100,y:50,label:"Co",color:"#d97706",name:"Cobalt"}], legend: "Cor=Corrin ring  Co=Cobalt center" },
    indications: { mostEffective: [{title:"Energy Metabolism",desc:"Primary - cellular energy production."},{title:"Neurological Function",desc:"Myelin and nerve health."},{title:"Methylation Support",desc:"Methylation cycle cofactor."}], effective: [{title:"Red Blood Cells",desc:"Erythropoiesis support."},{title:"Homocysteine",desc:"Cardiovascular health research."},{title:"Cognitive Function",desc:"Neurological cognitive support."}], moderate: [{title:"Mood",desc:"Neurotransmitter synthesis."},{title:"Sleep",desc:"Melatonin synthesis support."}] },
    dosing: { note: "Injectable B12 has superior bioavailability to oral forms for research protocols.", rows: [{goal:"General Support",dose:"500-1000 mcg",freq:"2-3x per week",route:"SC/IM"},{goal:"Therapeutic",dose:"1000-5000 mcg",freq:"1-2x per week",route:"IM"}], tips: ["Methylcobalamin preferred over cyanocobalamin for research","Injections provide rapid and complete absorption","Can be combined with B-complex for comprehensive B vitamin research"] },
    interactions: { note: "B12 interacts with methylation and energy pathways.", cards: [{slug:"nad",name:"NAD+",desc:"Complementary - both support energy metabolism.",effect:"Complementary"},{slug:"l-carnitine",name:"L-Carnitine",desc:"Supportive - both involved in mitochondrial energy production.",effect:"Supportive"}], stackNotes: ["B12 + NAD+ for comprehensive energy metabolism research","Methylcobalamin supports methylation alongside SAM"] },
    timeline: { phases: [{day:"Day 1-3",title:"Acute",desc:"Immediate energy improvement.",color:"blue",icon:"M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 1-4",title:"Saturation",desc:"Tissue B12 levels normalised.",color:"emerald",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"},{day:"Week 4-12",title:"Sustained",desc:"Consistent benefits maintained.",color:"purple",icon:"M5 13l4 4L19 7"}] },
    safety: { cards: [{label:"Essential Nutrient",text:"Excellent safety profile - water-soluble vitamin.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"},{label:"Well-Tolerated",text:"Minimal side effects at standard doses.",icon:"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",color:"emerald"}] },
    references: ["Herbert V, et al. Vitamin B12. Annu Rev Nutr. 1988;8:455-469.","Green R, et al. Vitamin B12 deficiency. Nat Rev Dis Primers. 2017;3:17040.","Wolffenbuttel BHR, et al. B12 deficiency. Eur J Endocrinol. 2019;180(1):R1-R14."],
  },
'''

new_content = content[:idx] + all_entries + content[idx:]
with open(FILE, 'w') as f:
    f.write(new_content)
print(f"Added batch with multiple compounds")
print(f"New file size: {len(new_content)} chars")
